<div id="accesslistModal" class="mmodal fade" tabindex="1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">Bundle</h4>
      </div>
      <form action="#" class="form-horizontal" id="accesslist">
        <div class="form-body">
          <div class="alert alert-danger display-hide">
            <button class="close" data-close="alert"></button>
            You have some form errors. Please check below.
          </div>
          <div class="alert alert-success display-hide">
            <button class="close" data-close="alert"></button>
            Your form validation is successful!
          </div>

          <div class="modal-body">
            <div class="scroller" style="height:150px" data-always-visible="1" data-rail-visible1="1">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
                      <?php  echo $this->formRow($formUserAccessList->get('accessName')); ?>
                      <span class="help-block">
                        Access Name
                      </span>
                    </div>
                  </div>
                </div>
                <!--/span-->
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
                      <?php  echo $this->formRow($formUserAccessList->get('permission')); ?>
                      <span class="help-block">
                        Permission
                      </span>
                    </div>
                  </div>
                </div>
              </div><!--/row  -->
            </div><!--/scroller  -->
            <div class="modal-footer">
              <button type="button" data-dismiss="modal" class="btn default">Close</button>
              <button type="submit" class="btn green">Save Changes</button>
            </div>
          </div><!--/modal-body  -->
      </div><!--/form-body  -->
    </form> <!--/form -->
  </div> <!--/modal content -->
</div> <!--/modal dialog -->
</div> <!--/class modal -->
