<?php

namespace DoctrineORMModule\Proxy\__CG__\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customers extends \Database\Entity\Customers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'customerId', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'companyName', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'branch', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'tradeName', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'tin', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'phone', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'email', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'website', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'secNo', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'consignee', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'franchisee', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'creditLimit', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'transactionLimit', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'percentCommission', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'customerStatus', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'category', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'customerType', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'paymentTerm', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'priceType', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'shippingMode', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'salesExecutive');
        }

        return array('__isInitialized__', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'customerId', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'companyName', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'branch', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'tradeName', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'tin', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'phone', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'email', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'website', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'secNo', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'consignee', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'franchisee', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'creditLimit', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'transactionLimit', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'percentCommission', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'customerStatus', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'category', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'customerType', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'paymentTerm', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'priceType', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'shippingMode', '' . "\0" . 'Database\\Entity\\Customers' . "\0" . 'salesExecutive');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCustomerId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCustomerId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerId', array());

        return parent::getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyName($companyName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyName', array($companyName));

        return parent::setCompanyName($companyName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyName', array());

        return parent::getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBranch($branch)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBranch', array($branch));

        return parent::setBranch($branch);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranch', array());

        return parent::getBranch();
    }

    /**
     * {@inheritDoc}
     */
    public function setTradeName($tradeName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTradeName', array($tradeName));

        return parent::setTradeName($tradeName);
    }

    /**
     * {@inheritDoc}
     */
    public function getTradeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTradeName', array());

        return parent::getTradeName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTin($tin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTin', array($tin));

        return parent::setTin($tin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTin', array());

        return parent::getTin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', array($website));

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', array());

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecNo($secNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecNo', array($secNo));

        return parent::setSecNo($secNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecNo', array());

        return parent::getSecNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsignee($consignee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsignee', array($consignee));

        return parent::setConsignee($consignee);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsignee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsignee', array());

        return parent::getConsignee();
    }

    /**
     * {@inheritDoc}
     */
    public function setFranchisee($franchisee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFranchisee', array($franchisee));

        return parent::setFranchisee($franchisee);
    }

    /**
     * {@inheritDoc}
     */
    public function getFranchisee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFranchisee', array());

        return parent::getFranchisee();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditLimit($creditLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditLimit', array($creditLimit));

        return parent::setCreditLimit($creditLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditLimit', array());

        return parent::getCreditLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionLimit($transactionLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionLimit', array($transactionLimit));

        return parent::setTransactionLimit($transactionLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionLimit', array());

        return parent::getTransactionLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercentCommission($percentCommission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercentCommission', array($percentCommission));

        return parent::setPercentCommission($percentCommission);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercentCommission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercentCommission', array());

        return parent::getPercentCommission();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerStatus($customerStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerStatus', array($customerStatus));

        return parent::setCustomerStatus($customerStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerStatus', array());

        return parent::getCustomerStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Database\Entity\Categories $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerType(\Database\Entity\CustomerTypes $customerType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerType', array($customerType));

        return parent::setCustomerType($customerType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerType', array());

        return parent::getCustomerType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentTerm(\Database\Entity\PaymentTerms $paymentTerm = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentTerm', array($paymentTerm));

        return parent::setPaymentTerm($paymentTerm);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentTerm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentTerm', array());

        return parent::getPaymentTerm();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceType(\Database\Entity\PriceTypes $priceType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceType', array($priceType));

        return parent::setPriceType($priceType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceType', array());

        return parent::getPriceType();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMode(\Database\Entity\ShippingModes $shippingMode = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMode', array($shippingMode));

        return parent::setShippingMode($shippingMode);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMode', array());

        return parent::getShippingMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalesExecutive(\Database\Entity\Users $salesExecutive = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalesExecutive', array($salesExecutive));

        return parent::setSalesExecutive($salesExecutive);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalesExecutive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalesExecutive', array());

        return parent::getSalesExecutive();
    }

}
