<?php

namespace DoctrineORMModule\Proxy\__CG__\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Products extends \Database\Entity\Products implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'productId', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'productCode', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'productName', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'productDescription', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'size', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'weight', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'productStatus', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'partNumber', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'blCode', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'printedCode', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'brand', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'classification', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'paymentTerm', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'supplier');
        }

        return array('__isInitialized__', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'productId', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'productCode', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'productName', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'productDescription', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'size', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'weight', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'productStatus', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'partNumber', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'blCode', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'printedCode', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'brand', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'classification', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'paymentTerm', '' . "\0" . 'Database\\Entity\\Products' . "\0" . 'supplier');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Products $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProductId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProductId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductId', array());

        return parent::getProductId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductCode($productCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductCode', array($productCode));

        return parent::setProductCode($productCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCode', array());

        return parent::getProductCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductName($productName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductName', array($productName));

        return parent::setProductName($productName);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductName', array());

        return parent::getProductName();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductDescription($productDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductDescription', array($productDescription));

        return parent::setProductDescription($productDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductDescription', array());

        return parent::getProductDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setSize($size)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', array($size));

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', array());

        return parent::getSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeight($weight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeight', array($weight));

        return parent::setWeight($weight);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeight', array());

        return parent::getWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductStatus($productStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductStatus', array($productStatus));

        return parent::setProductStatus($productStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductStatus', array());

        return parent::getProductStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartNumber($partNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartNumber', array($partNumber));

        return parent::setPartNumber($partNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartNumber', array());

        return parent::getPartNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlCode($blCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlCode', array($blCode));

        return parent::setBlCode($blCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlCode', array());

        return parent::getBlCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrintedCode($printedCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrintedCode', array($printedCode));

        return parent::setPrintedCode($printedCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrintedCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrintedCode', array());

        return parent::getPrintedCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand(\Database\Entity\Brands $brand = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', array($brand));

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', array());

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassification(\Database\Entity\Classifications $classification = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassification', array($classification));

        return parent::setClassification($classification);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassification', array());

        return parent::getClassification();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentTerm(\Database\Entity\PaymentTerms $paymentTerm = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentTerm', array($paymentTerm));

        return parent::setPaymentTerm($paymentTerm);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentTerm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentTerm', array());

        return parent::getPaymentTerm();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupplier(\Database\Entity\Suppliers $supplier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupplier', array($supplier));

        return parent::setSupplier($supplier);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplier', array());

        return parent::getSupplier();
    }

}
