<!-- BEGIN PAGE LEVEL STYLES -->
<?php
$this->headLink()
->appendStylesheet($this->basePath('/assets/plugins/select2/select2.css'))
->appendStylesheet($this->basePath('/assets/plugins/select2/select2-metronic.css'))
->appendStylesheet($this->basePath('/assets/plugins/data-tables/DT_bootstrap.css'))
?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-reorder"></i>Payment Records
    </div>
    <div class="tools">
      <a href="javascript:;" class="collapse">
      </a>
      <a href="#portlet-config" data-toggle="modal" class="config">
      </a>
      <a href="javascript:;" class="reload">
      </a>
      <a href="javascript:;" class="remove">
      </a>
    </div>
  </div>
  <div class="portlet-body form">
    <!-- BEGIN FORM-->
    <form action="#" class="form-horizontal">
      <div class="form-body">
        <h4 class="form-section">Records  </h4>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('paymentNo')); ?>
                <span class="help-block">
                  Payment Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->

          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($form->get('performaInvoiceNo')); ?>
                <span class="help-block">
                  Performa Invoice Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('cmNo')); ?>
                <span class="help-block">
                  CM Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($form->get('rmrNo')); ?>
                <span class="help-block">
                  RMR Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>


        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('drNo')); ?>
                <span class="help-block">
                  DR Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($form->get('siNo')); ?>
                <span class="help-block">
                  SI Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('soNo')); ?>
                <span class="help-block">
                  SO Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($form->get('transactionTypes[transactionTypeId]')); ?>
                <span class="help-block">
                  Transaction Types
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>


        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('customers[customerId]')); ?>
                <span class="help-block">
                  Customer
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($form->get('deliveryDates[deliveryDateId]')); ?>
                <span class="help-block">
                  Delivery Date
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('vatPercentage[vatPercentageId]')); ?>
                <span class="help-block">
                  Vat Percentage
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 right">

              </div>
            </div>
          </div>
          <!--/span-->
        </div>


        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('items')); ?>
                <span class="help-block">
                  Items
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 right">

              </div>
            </div>
          </div>
          <!--/span-->
        </div>


        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('sales')); ?>
                <span class="help-block">
                  Sales
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">

              </div>
            </div>
          </div>
          <!--/span-->
        </div>


        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('vat')); ?>
                <span class="help-block">
                  VAT
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">

              </div>
            </div>
          </div>
          <!--/span-->
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('transactionTypes[transactionTypeId]')); ?>
                <span class="help-block">
                  Total
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>
        <!-- BEGIN PAGE CONTENT-->

      </div>      <!--/FORM BODY  -->

      <div class="form-actions fluid">
        <div class="row">
          <div class="col-md-6">
            <div class="col-md-offset-3 col-md-9">
              <button type="button" class="btn green">Save and Send</button>
              <button type="button" class="btn default">Cancel</button>
            </div>
          </div>
          <div class="col-md-6">
          </div>
        </div>
      </div>
    </form>
    <!-- END FORM-->
  </div>
</div>


<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<?php
$this->inlineScript()
->appendFile($this->basePath('/assets/scripts/product.js'))
?>
<?php $this->inlineScript()->captureStart() ?>
jQuery(document).ready(function() {
  App.init();
  Product.init();
  ComponentsEditors.init();
  $('.tags').tagsInput({
    width: '100%',
  });
});
<?php $this->inlineScript()->captureEnd() ?>
