<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet box grey">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-edit"></i>User List
							</div>
							<div class="tools">
								<a href="javascript:;" class="collapse">
								</a>
								<a href="#portlet-config" data-toggle="modal" class="config">
								</a>
								<a href="/" class="reload">
								</a>
								<a href="javascript:;" class="remove">
								</a>
							</div>
						</div>
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="btn-group">
									<a class="btn green" href="/user/add">
									Add New <i class="fa fa-plus"></i>
									</a>
								</div>
							</div>
							<table class="main table table-striped table-hover table-bordered" id="users_table">
							<thead>
							<tr>
								<th>ID</th>
								<th>Full Name</th>
								<th>Username</th>
								<th>Position</th>
								<th>Email</th>
								<th>Mobile</th>
								<th>Status</th>
								<th>Action</th>
							</tr>
							</thead>
							<tbody>
							<?php foreach ($records as $record) : ?>
								 <tr>
									 <td><?php echo $record->getUserId() ?></td>
									 <td><?php echo $record->getFullName() ?></td>
									 <td><?php echo $record->getUserName() ?></td>
									 <td><?php echo $record->getDesignation()->getDesignationName() ?></td>
									 <td><?php echo $record->getEmail() ?></td>
									 <td><?php echo $record->getMobile() ?></td>
									 <td><?php echo $record->getUserStatus() ?></td>
									 <td><a class="edit" href="<?php echo $this->basePath('/user/edit/'.$record->getUserId()) ?>">Edit</a></td>
								 </tr>
							<?php endforeach; ?>
							</tbody>
							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->

<!-- BEGIN PAGE LEVEL PLUGINS -->
