<!-- BEGIN PAGE LEVEL STYLES -->
<?php
$this->headLink()
->appendStylesheet($this->basePath('/assets/plugins/select2/select2.css'))
->appendStylesheet($this->basePath('/assets/plugins/select2/select2-metronic.css'))
->appendStylesheet($this->basePath('/assets/plugins/data-tables/DT_bootstrap.css'))
?>
<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>PURCHASE ORDER
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse">
			</a>
			<a href="#portlet-config" data-toggle="modal" class="config">
			</a>
			<a href="javascript:;" class="reload">
			</a>
			<a href="javascript:;" class="remove">
			</a>
		</div>
	</div>
	<div class="portlet-body form">
		<!-- BEGIN FORM-->
		<form action="#" class="form-horizontal" id="customer_add">
			<div class="form-body">
			<div class="alert alert-danger display-hide">
						<button class="close" data-close="alert"></button>
							You have some form errors. Please check below.
					</div>
					<div class="alert alert-success display-hide">
						<button class="close" data-close="alert"></button>
							Your form validation is successful!
					</div>
				<div class="row">
				<br />
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($purchaseForm->get('categories[categoryId]')); ?>
								<span class="col-md-12 control-label">
									Purchase ID
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('customerTypes[customerTypeId]')); ?>
								<span class="col-md-12 control-label">
									Supplier ID
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('companyName')); ?>
								<span class="col-md-12 control-label">
									Reference Number
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('branch')); ?>
								<span class="col-md-12 control-label">
									Purchase Date
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('tradeName')); ?>
								<span class="col-md-12 control-label">
									Expected Arrival Date
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('customerTypes[customerTypeId]')); ?>
								<span class="col-md-12 control-label">
									Purchase Status
								</span>
									
							</div>
						</div>
					</div>
	
	<!-- 	BEGIN CONTACT -->
	<div class="portlet box grey">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i>Purchase Item
			</div>
			<div class="tools">
				<a href="javascript:;" class="collapse">
				</a>
				<a href="#portlet-config" data-toggle="modal" class="config">
				</a>
				<a href="javascript:;" class="reload">
				</a>
				<a href="javascript:;" class="remove">
				</a>
			</div>
		</div>
		<div class="portlet-body form">
			<!-- BEGIN FORM-->
				<div class="form-body">
					<div class="row">
					<br />
						<div class="col-md-2"></div>
						<div class="col-md-8" >
							<div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-left: 0px;">
								<button type="button" data-toggle="modal" href="#contactModal" class="btn-sm green custom-left">Add New
									<i class="fa fa-plus"></i>
								</button>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-right: 0px;">
								
							</div>
						</div>
						<div class="col-md-2"></div>
					</div>
					<div class="form-group">
						<div class="col-md-2"></div>
						<div class="col-md-8">
							<div class="row">
								<br />
								<div class="col-md-12">
									<div class="portlet-body flip-scroll">
										<table id="contactTable" class="table table-bordered table-condensed flip-content">
											<thead class="flip-content bg-grey">
											<tr>
												<th width="20%">Name</th>
												<th>Position</th>
												<th>Mobile</th>
												<th>Email</th>
												<th width="12%">Delete</th>
											</tr>
											</thead>
											<tbody>
											</tbody>
											</table>
										</div>
								</div>
							</div>
						</div>
						<div class="col-md-2"></div>
					</div>
				</div>
			<!-- END FORM-->
		</div>
	</div>
<!-- 	END CONTACT -->

				<!-- BEGIN PAGE CONTENT-->

			</div>
			<div class="form-actions fluid">
				<div class="row">
					<div class="col-md-6">
						<div class="col-md-offset-3 col-md-9">
							<button type="submit" class="btn green">Submit</button>
							<button type="button" class="btn default">Cancel</button>
						</div>
					</div>
					<div class="col-md-6">
					</div>
				</div>
			</div>
		</form>
		<!-- END FORM-->
	</div>
</div>

<div>
<?php echo $this->render('customer/address') ?>
</div>
<div>
<?php echo $this->render('customer/contact') ?>
</div>
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="/assets/plugins/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/assets/plugins/data-tables/DT_bootstrap.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/assets/scripts/core/app.js"></script>
<?php
$this->inlineScript()
->appendFile($this->basePath('/assets/scripts/ajax/generic.js'))
->appendFile($this->basePath('/assets/scripts/customer.js'))
->appendFile($this->basePath('/assets/scripts/contact.js'))
->appendFile($this->basePath('/assets/scripts/address.js'))

?>
<?php $this->inlineScript()->captureStart() ?>
jQuery(document).ready(function() {
	Customer.init();
	Contact.init();
	Address.init();

	
});
<?php $this->inlineScript()->captureEnd() ?>
