<!-- BEGIN PAGE LEVEL STYLES -->
<?php 
   $this->headLink()
        ->appendStylesheet($this->basePath('/assets/plugins/select2/select2.css'))
        ->appendStylesheet($this->basePath('/assets/plugins/select2/select2-metronic.css'))
        ->appendStylesheet($this->basePath('/assets/plugins/data-tables/DT_bootstrap.css'))
?>
<div class="tab-pane " id="tab_2">
	<div class="portlet box green">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i>Form Sample
			</div>
			<div class="tools">
				<a href="javascript:;" class="collapse">
				</a>
				<a href="#portlet-config" data-toggle="modal" class="config">
				</a>
				<a href="javascript:;" class="reload">
				</a>
				<a href="javascript:;" class="remove">
				</a>
			</div>
		</div>
		<div class="portlet-body form">
			<!-- BEGIN FORM-->
			<form action="#" class="form-horizontal">
				<div class="form-body">
					<h3 class="form-section">Person Info</h3>
					<div class="row">
						<div class="col-md-6">
							<div class="form-group col-md-12">
								<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 right">
									<input type="text" class="form-control" placeholder="Chee Kin">
									<span class="help-block">
										 First Name
									</span>
								</div>
							</div>
						</div>
							<!--/span-->
						<div class="col-md-6">
							<div class="form-group select">
								<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 left select">
									<select name="foo" class="select2me form-control">
										<option value="1">Abc</option>
										<option value="1">Abc</option>
										<option value="1">This is a really long value that breaks the fluid design for a select2</option>
									</select>
									<span class="help-block">
										 Last Name
									</span>
								</div>
							</div>
						</div>
						<!--/span-->
					</div>

				</div>
				<div class="form-actions fluid">
					<div class="row">
						<div class="col-md-6">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" class="btn green">Submit</button>
								<button type="button" class="btn default">Cancel</button>
							</div>
						</div>
						<div class="col-md-6">
						</div>
					</div>
				</div>
			</form>
			<!-- END FORM-->
		</div>
	</div>
</div>
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="/assets/plugins/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/assets/plugins/data-tables/DT_bootstrap.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/assets/scripts/core/app.js"></script>
<?php 
    $this->inlineScript()
        ->appendFile($this->basePath('/assets/scripts/datatable/realms.index.js'))
        ->appendFile($this->basePath('/assets/scripts/ajax/realms.js'))
        ->appendFile($this->basePath('/assets/scripts/ajax/generic.js'))
?>
<?php $this->inlineScript()->captureStart() ?>
    jQuery(document).ready(function() {    
        App.init();
        TableEditable.init();
    });
<?php $this->inlineScript()->captureEnd() ?>
							