<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet box grey">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-edit"></i>Product List
							</div>
							<div class="tools">
								<a href="javascript:;" class="collapse">
								</a>
								<a href="#portlet-config" data-toggle="modal" class="config">
								</a>
								<a href="/" class="reload">
								</a>
								<a href="javascript:;" class="remove">
								</a>
							</div>
						</div>
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="btn-group">
									<a id="sample_editable_1_new" class="btn green" href="/product/add">
									Add New <i class="fa fa-plus"></i>
									</a>
								</div>
								<div class="btn-group pull-right">
									<button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
									</button>
									<ul class="dropdown-menu pull-right">
										<li>
											<a href="#">
												 Print
											</a>
										</li>
										<li>
											<a href="#">
												 Save as PDF
											</a>
										</li>
										<li>
											<a href="#">
												 Export to Excel
											</a>
										</li>
									</ul>
								</div>
							</div>
							<table class="table table-striped table-hover table-bordered" id="sample_editable_1">
							<thead>
							<tr>
							    <th>Code</th>
								<th>Name</th>
								<th>Description</th>
								<th>Classification</th>
								<th>Category</th>
								<th>Brand</th>
								<th>Supplier</th>
								<th>Size</th>
								<th>Weight</th>
								<th>Status</th>
								<th>Action</th>
							</tr>
							</thead>
							<tbody>
              
							<!-- <?php foreach ($records as $record) : ?> -->
                            	 <tr>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td><a class="edit" href="javascript:;">Edit</a></td>
                            	 </tr>
                            <!-- <?php endforeach; ?> -->
							</tbody>
							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->

<!-- BEGIN PAGE LEVEL PLUGINS -->
<?php 
    $this->inlineScript()
        ->appendFile($this->basePath('/assets/scripts/datatable/Table.js'))
        ->appendFile($this->basePath('/assets/scripts/ajax/realms.js'))
        ->appendFile($this->basePath('/assets/scripts/ajax/generic.js'))
?>
<?php $this->inlineScript()->captureStart() ?>
    jQuery(document).ready(function() {    
        Table.init();
    });
<?php $this->inlineScript()->captureEnd() ?>