
<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>CUSTOMER PROFILE
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse"> </a> <a
				href="#portlet-config" data-toggle="modal" class="config"> </a> <a
				href="javascript:;" class="reload"> </a> <a href="javascript:;"
				class="remove"> </a>
		</div>
	</div>
	<div class="portlet-body form">
		<!-- BEGIN FORM-->
		<form action="/customer/add" class="form-horizontal" id="customer_add" method="post">
			<div class="form-body">
				<div class="alert alert-danger display-hide">
					<button class="close" data-close="alert"></button>
					You have some form errors. Please check below.
				</div>
				<div class="alert alert-success display-hide">
					<button class="close" data-close="alert"></button>
					Your form validation is successful!
				</div>
				<div class="row">
					<br />
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('category[categoryId]')); ?>
								<span class="col-md-12 control-label"> Category </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('customerType[customerTypeId]')); ?>
								<span class="col-md-12 control-label"> Type </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('companyName')); ?>
								<span class="col-md-12 control-label"> Company Name </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('branch')); ?>
								<span class="col-md-12 control-label"> Branch Location </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('tradeName')); ?>
								<span class="col-md-12 control-label"> Trade Name </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('tinNumber')); ?>
								<span class="col-md-12 control-label"> TIN </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('phone')); ?>
								<span class="col-md-12 control-label"> Phone </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('email')); ?>
								<span class="col-md-12 control-label"> Email </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('website')); ?>
								<span class="col-md-12 control-label"> Website </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('secNumber')); ?>
								<span class="col-md-12 control-label"> SEC Number </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>


				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<label class="checkbox"> <!-- <input type="checkbox" name="consignee" value=""> -->
								<?php  echo $this->formRow($customerForm->get('consignee')); ?>
								Consignee</label>
							</div>
						</div>
					</div>


					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<label class="checkbox"> <!-- <input type="checkbox" name="consignee" value=""> -->
								<?php  echo $this->formRow($customerForm->get('franchise')); ?>
								Franchise</label>
							</div>
						</div>
					</div>
				</div>
				<!--/row  -->




				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('creditLimit')); ?>
								<span class="col-md-12 control-label"> Credit Limit </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left select">
								<?php  echo $this->formRow($customerForm->get('unpaidTransactionLimit')); ?>
								<span class="col-md-12 control-label"> Unpaid Transaction Limit
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->


				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('paymentTerm[paymentTermId]')); ?>
								<span class="col-md-12 control-label"> Payment Terms </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left select">
								<?php  echo $this->formRow($customerForm->get('permanentDiscount')); ?>
								<span class="col-md-12 control-label"> Permanent Discount </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->


				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('shippingMode[shippingModeId]')); ?>
								<span class="col-md-12 control-label"> Shipping Mode </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left select">
								<?php  echo $this->formRow($customerForm->get('salesExecutive[userId]')); ?>
								<span class="col-md-12 control-label"> Sales Executive </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('priceType[priceTypeId]')); ?>
								<span class="col-md-12 control-label"> Price Type </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left select">
								<?php  echo $this->formRow($customerForm->get('customerStatus')); ?>
								<span class="col-md-12 control-label"> Customer Status </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->

				<!-- 	BEGIN ADDRESS -->
				<div class="portlet box grey">
					<div class="portlet-title">
						<div class="caption">
							<i class="fa fa-reorder"></i>ADDRESS
						</div>
						<div class="tools">
							<a href="javascript:;" class="collapse"> </a> <a
								href="#portlet-config" data-toggle="modal" class="config"> </a>
							<a href="javascript:;" class="reload"> </a> <a
								href="javascript:;" class="remove"> </a>
						</div>
					</div>
					<div class="portlet-body form">
						<!-- BEGIN FORM-->
						<div class="row">
							<br />
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
										<label class="checkbox custom-left">
							<?php  echo $this->formRow($addressForm->get('shipping')); ?>
							Shipping</label> <label class="checkbox custom-right">
							<?php  echo $this->formRow($addressForm->get('billing')); ?>
							Billing</label> <span class="col-md-12 control-label"> Address Type
									 </span>
									</div>
								</div>
							</div>
							<!--/span-->
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
										<?php echo $this->formRow($addressForm->get('streetLandmark')); ?>
										<span class="col-md-12 control-label"> Street/Landmark </span>
									</div>
								</div>
							</div>
						</div>
						<!--end of row  -->

						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
										<?php echo $this->formRow($addressForm->get('cities[cityId]')); ?>
										<span class="col-md-12 control-label"> City </span>
									</div>
								</div>
							</div>
							<!--/span-->
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
										<?php echo $this->formRow($addressForm->get('provinces[provinceId]')); ?>
										<span class="col-md-12 control-label"> Province </span>
									</div>
								</div>
							</div>
						</div>
						<!--end of row  -->

						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
										<?php echo $this->formRow($addressForm->get('countries[countryId]')); ?>
										<span class="col-md-12 control-label"> Country </span>
									</div>
								</div>
							</div>
							<!--/span-->
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
										<?php echo $this->formRow($addressForm->get('zipcode')); ?>
										<span class="col-md-12 control-label"> Zipcode </span>
									</div>
								</div>
							</div>
						</div>
						<!--end of row  -->

						<!-- END FORM-->
					</div>
				</div>
				<!-- 	END ADDRESS -->

				<!-- 	BEGIN CONTACT -->
				<div class="portlet box grey">
					<div class="portlet-title">
						<div class="caption">
							<i class="fa fa-reorder"></i>CONTACT PERSON
						</div>
						<div class="tools">
							<a href="javascript:;" class="collapse"> </a> <a
								href="#portlet-config" data-toggle="modal" class="config"> </a>
							<a href="javascript:;" class="reload"> </a> <a
								href="javascript:;" class="remove"> </a>
						</div>
					</div>
					<div class="portlet-body form">
						<!-- BEGIN FORM-->
						<div class="form-body">
							<div class="row">
								<br />
 								<div class="col-md-2"></div>
 								<div class="col-md-8"> -->
 									<div class="col-xs-6 col-sm-6 col-md-6 col-md-6" 
 										style="padding-left: 0px;">
										<button type="button" data-toggle="modal" href="#contactModal"
											class="btn-sm green custom-left">
											Add New <i class="fa fa-plus"></i>
										</button>
									</div>
									<div class="col-xs-6 col-sm-6 col-md-6 col-md-6"
 										style="padding-right: 0px;"></div>
								</div>
								<div class="col-md-2"></div>
							</div>
							<div class="form-group">
								<div class="col-md-2"></div>
								<div class="col-md-8">
									<div class="row">
										<br />
										<div class="col-md-12">
											<div class="portlet-body flip-scroll">
												<table id="contactTable"
													class="table table-bordered table-condensed flip-content">
													<thead class="flip-content bg-grey">
														<tr>
															<th width="20%">Name</th>
															<th>Position</th>
															<th>Mobile</th>
															<th>Email</th>
															<th width="12%">Delete</th>
														</tr>
													</thead>
													<tbody>
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
								<div class="col-md-2"></div>
							</div>
						</div>
						<!-- END FORM-->
					</div>
				</div>
				<!-- 	END CONTACT -->

				<!-- BEGIN PAGE CONTENT-->

			</div><!-- /portlet-body form -->
			
			<div class="form-actions fluid">
				<div class="row">
					<div class="col-md-6">
						<div class="col-md-offset-3 col-md-9">
							<button type="submit" class="btn green">Submit</button>
							<button type="button" class="btn default">Cancel</button>
						</div>
					</div>
					<div class="col-md-6"></div>
				</div>
			</div>
		</form>
		<!-- END FORM-->
	</div>
</div>

<div>
<?php echo $this->render('customer/address') ?>
</div>
<div>
<?php echo $this->render('customer/contact') ?>
</div>

<!-- <script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script> -->
<!-- <script type="text/javascript" src="/assets/plugins/data-tables/jquery.dataTables.js"></script> -->
<!-- <script type="text/javascript" src="/assets/plugins/data-tables/DT_bootstrap.js"></script> -->
<!-- <script src="/assets/scripts/core/app.js"></script> -->

<?php
$this->inlineScript()
->appendFile($this->basePath('/assets/scripts/ajax/generic.js'))
->appendFile($this->basePath('/assets/scripts/customer.js'))
->appendFile($this->basePath('/assets/scripts/contact.js'))
->appendFile($this->basePath('/assets/scripts/address.js'))

?>
<?php $this->inlineScript()->captureStart() ?>
jQuery(document).ready(function() {
	Customer.init();
	Contact.init();
	Address.init();

	
});
<?php $this->inlineScript()->captureEnd() ?>
