<!-- BEGIN PAGE LEVEL STYLES -->
<?php
$this->headLink()
->appendStylesheet($this->basePath('/assets/plugins/select2/select2.css'))
->appendStylesheet($this->basePath('/assets/plugins/select2/select2-metronic.css'))
->appendStylesheet($this->basePath('/assets/plugins/data-tables/DT_bootstrap.css'))
?>
<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>Customer Profile
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse">
			</a>
			<a href="#portlet-config" data-toggle="modal" class="config">
			</a>
			<a href="javascript:;" class="reload">
			</a>
			<a href="javascript:;" class="remove">
			</a>
		</div>
	</div>
	<div class="portlet-body form">
		<!-- BEGIN FORM-->
		<form action="#" class="form-horizontal">
			<div class="form-body">
				<h4 class="form-section">Add Customer</h4>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('categories[categoryId]')); ?>
								<span class="col-md-12 control-label">
									Category
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('customerTypes[customerTypeId]')); ?>
								<span class="col-md-12 control-label">
									Type
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('companyName')); ?>
								<span class="col-md-12 control-label">
									Company Name
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('branch')); ?>
								<span class="col-md-12 control-label">
									Branch
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('tradeName')); ?>
								<span class="col-md-12 control-label">
									Trade Name
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('tinNumber')); ?>
								<span class="col-md-12 control-label">
									TIN
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('phone')); ?>
								<span class="col-md-12 control-label">
									Phone
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('email')); ?>
								<span class="col-md-12 control-label">
									Email
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('website')); ?>
								<span class="col-md-12 control-label">
									Website
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($customerForm->get('secNumber')); ?>
								<span class="col-md-12 control-label">
									Sec. Number
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>


<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
				<label class="checkbox">
				<!-- <input type="checkbox" name="consignee" value=""> -->
				<?php  echo $this->formRow($customerForm->get('consignee')); ?>
				Consignee</label>
			</div>
</div>
	</div>


	<div class="col-md-6">
		<div class="form-group">
			<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
				<label class="checkbox">
				<!-- <input type="checkbox" name="consignee" value=""> -->
				<?php  echo $this->formRow($customerForm->get('franchise')); ?>
				Franchise</label>
			</div>
		</div>
		</div>
</div><!--/row  -->




				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('creditLimit')); ?>
								<span class="col-md-12 control-label">
									Credit Limit
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left select">
								<?php  echo $this->formRow($customerForm->get('unpaidTransactionLimit')); ?>
								<span class="col-md-12 control-label">
									Unpaid Transaction Limit
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div><!--/row-->


				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('paymentTerms[paymentTermId]')); ?>
								<span class="col-md-12 control-label">
									Payment Terms
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left select">
								<?php  echo $this->formRow($customerForm->get('percentCommission')); ?>
								<span class="col-md-12 control-label">
									%Commission
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div><!--/row-->


				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('shippingModes[shippingModeId]')); ?>
								<span class="col-md-12 control-label">
									Shipping Mode
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left select">
								<?php  echo $this->formRow($customerForm->get('users[userId]')); ?>
								<span class="col-md-12 control-label">
									Sales Executive
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div><!--/row-->

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($customerForm->get('priceTypes[priceTypeId]')); ?>
								<span class="col-md-12 control-label">
									Price Type
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left select">
								<?php  echo $this->formRow($customerForm->get('customerStatus')); ?>
								<span class="col-md-12 control-label">
									Customer Status
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div><!--/row-->




					<div class="row">
						<div class="col-md-2"></div>
						<div class="col-md-8">
							<hr/>
							<div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-left: 0px;">
								<h4 class="">Address</h4>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-right: 0px;">
								<button type="button" data-toggle="modal" href="#addressModal" class="btn-sm green custom-right">
							Add New
								<i class="fa fa-plus"></i>
							</button>
							</div>
						</div>
						<div class="col-md-2"></div>
					</div>

				<div class="form-group">
						<div class="col-md-2"></div>
						<div class="col-md-8">
							<div class="row">
								<div class="col-md-12">
										<div class="portlet-body flip-scroll">
											<table class="table table-bordered table-condensed flip-content">
											<thead class="flip-content bg-grey">
											<tr>
												<th width="20%">Address Type</th>
												<th>Stree/Landmark</th>
												<th>City</th>
												<th>Province</th>
												<th>Country</th>
												<th>Zipcode</th>
												<th width="12%">Delete</th>
											</tr>
											</thead>
											<tbody>
											</tbody>
											</table>
										</div>
								</div>
							</div>
						</div>
						<div class="col-md-2"></div>
					</div>



				<div class="row">
						<div class="col-md-2"></div>
						<div class="col-md-8">
							<hr/>
							<div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-left: 0px;">
								<h4 class="">Contact</h4>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-right: 0px;">
								<button type="button" data-toggle="modal" href="#contactModal" class="btn-sm green custom-right">
							Add New
								<i class="fa fa-plus"></i>
							</button>
							</div>
						</div>
						<div class="col-md-2"></div>
					</div>

				<div class="form-group">
						<div class="col-md-2"></div>
						<div class="col-md-8">
							<div class="row">
								<div class="col-md-12">
										<div class="portlet-body flip-scroll">
											<table class="table table-bordered table-condensed flip-content">
											<thead class="flip-content bg-grey">
											<tr>
												<th width="20%">Position</th>
												<th>Primary</th>
												<th>Full Name</th>
												<th>Email</th>
												<th>Phone</th>
												<th width="12%">Delete</th>
											</tr>
											</thead>
											<tbody>
											</tbody>
											</table>
										</div>
								</div>
							</div>
						</div>
						<div class="col-md-2"></div>
					</div>
					



				<!-- BEGIN PAGE CONTENT-->

			</div>
			<div class="form-actions fluid">
				<div class="row">
					<div class="col-md-6">
						<div class="col-md-offset-3 col-md-9">
							<button type="submit" class="btn green">Submit</button>
							<button type="button" class="btn default">Cancel</button>
						</div>
					</div>
					<div class="col-md-6">
					</div>
				</div>
			</div>
		</form>
		<!-- END FORM-->
	</div>
</div>

<div>
<?php echo $this->render('customer/address') ?>
</div>
<div>
<?php echo $this->render('customer/contact') ?>
</div>
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="/assets/plugins/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/assets/plugins/data-tables/DT_bootstrap.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/assets/scripts/core/app.js"></script>
<?php
$this->inlineScript()
->appendFile($this->basePath('/assets/scripts/ajax/generic.js'))
->appendFile($this->basePath('/assets/scripts/customer.js'))
?>
<?php $this->inlineScript()->captureStart() ?>
jQuery(document).ready(function() {
	App.init();
	Customer.init();
});
<?php $this->inlineScript()->captureEnd() ?>
