<!-- BEGIN EXAMPLE TABLE PORTLET-->
<div class="portlet box grey">
  <div class="portlet-title">
	<div class="caption">
	  <i class="fa fa-edit"></i>CUSTOMER LIST
	</div>
	<div class="tools">
	  <a href="javascript:;" class="collapse"> </a> <a
	  href="#portlet-config" data-toggle="modal" class="config"> </a> <a
	  href="/" class="reload"> </a> <a href="javascript:;" class="remove">
	  </a>
	</div>
  </div>
  <div class="portlet-body">
	<div class="table-toolbar">
	  <div class="btn-group">
		<a class="btn green" href="/customer/add"> Add New <i class="fa fa-plus"></i>
		</a>
	  </div>
	</div>
	<table class="main table table-striped table-hover table-bordered" id="customers_table">
	<thead>
	  <tr>
		<th>Category</th>
		<th>Type</th>
		<th>Name</th>
		<th>Trade Name</th>
		<th>Branch</th>
		<th>TIN</th>
		<th>Phone</th>
		<th>Email</th>
		<th>Website</th>
		<th>SEC No</th>
		<th>Credit Limit</th>
		<th>Transaction Limit</th>
		<th>Payment Term</th>
		<th>Shipping Mode</th>
		<th>Commission</th>
		<th>Sales Executive</th>
		<th>Price Type</th>
		<th>Status</th>
		<th></th>
		<th></th>
	  </tr>
	</thead>
	<tbody>
	  
	  <?php  foreach ($records as $record) :?>
		<tr> 
		  <td><?php echo $record->getCategory() ? $record->getCategory()->getCategoryName() : "" ?></td>
		  <td><?php echo $record->getCustomerType() ? $record->getCustomerType()->getCustomerTypeName() : "" ?></td>
		  <td><?php  echo $record->getCompanyName() ?></td>
		  <td><?php  echo $record->getTradeName() ?></td>
		  <td><?php  echo $record->getBranch() ?></td>
		  <td><?php  echo $record->getTin() ?></td>
		  <td><?php  echo $record->getPhone() ?></td>
		  <td><?php  echo $record->getEmail() ?></td>
		  <td><?php  echo $record->getWebsite() ?></td>
		  <td><?php  echo $record->getSecNo() ?></td>
		  <td><?php  echo $record->getCreditLimit() ?></td>
		  <td><?php  echo $record->getTransactionLimit() ?></td>
		  <td><?php  echo $record->getPaymentTerm() ? $record->getPaymentTerm()->getPaymentTermName() : "" ?></td>
		  <td><?php  echo $record->getShippingMode() ? $record->getShippingMode()->getShippingModeName() : "" ?></td>
		  <td><?php  echo $record->getPercentCommision() ?></td>
		  <td><?php  echo $record->getSalesExecutive() ? $record->getSalesExecutive()->getUserName() : "" ?></td>
		  <td><?php  echo $record->getPriceType() ? $record->getPriceType()->getPriceTypeName() : "" ?></td>
		  <td><?php  echo $record->getCustomerStatus() ?></td>
		  <td><a class="edit"
			href=" <?php // echo  $this->basePath('/customer/edit'.$record->getCustomerId()) ?> ">Edit</a></td>
			<td><a class="delete"
			  href=" <?php // echo $this->basePath('/customer'.$record->getCustomerId()) ?> ">Delete</a></td>
			</tr>
		  <?php endforeach; ?>
		</tbody>
	  </table>
	</div>
  </div>
  
  
