
<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>Shipment
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse"></a> <a
				href="#portlet-config" data-toggle="modal" class="config"></a> <a
				href="javascript:;" class="reload"></a> <a href="javascript:;"
				class="remove"></a>
		</div>
	</div>
	<div class="portlet-body form">
		<form action="#" class="form-horizontal" id="shipment_add">
			<div class="form-body">
				<div class="alert alert-danger display-hide">
					<button class="close" data-close="alert"></button>
					You have some form errors. Please check below.
				</div>
				<div class="alert alert-success display-hide">
					<button class="close" data-close="alert"></button>
					Your form validation is successful!
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($formShipment->get('shipmentId')); ?>
								<span class="col-md-12 control-label">Shipment</span>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($formShipment->get('supplierId')); ?>
								<span class="col-md-12 control-label">Supplier</span>
							</div>
						</div>
					</div>
				</div>
				
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($formShipment->get('referenceNo')); ?>
								<span class="col-md-12 control-label">Reference Number</span>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
							
								<span class="col-md-12 control-label"></span>
							</div>
						</div>
					</div>
				</div>
				
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($formShipment->get('shipmentStatus')); ?>
								<span class="col-md-12 control-label">Shipment Status</span>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($formShipment->get('arrivalDate')); ?>
								<span class="col-md-12 control-label">Arrival Date</span>
							</div>
						</div>
					</div>
				</div>
				
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<div class="col-md-2 col-lg-2 "></div>
							<div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 ">
								<?php echo $this->formRow($formShipment->get('notes')); ?>
								<span class="col-md-12 control-label">Notes</span>
							</div>
							<div class="col-md-2 col-lg-2 "></div>
						</div>
					</div>
				</div>
				
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($formShipment->get('confirmedBy')); ?>
								<span class="col-md-12 control-label">Confirmed By</span>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($formShipment->get('approveBy')); ?>
								<span class="col-md-12 control-label">Approve By</span>
							</div>
						</div>
					</div>
				</div>
       				
			<div class="form-group">
				<div class="col-md-1"></div>
				<div class="col-md-10">
					<div class="row">
				<div class="col-md-12">
					
				<!-- 	BEGIN PRICE -->
	<div class="portlet box grey">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i>Shipment Item
			</div>
			<div class="tools">
				<a href="javascript:;" class="collapse">
				</a>
				<a href="#portlet-config" data-toggle="modal" class="config">
				</a>
				<a href="javascript:;" class="reload">
				</a>
				<a href="javascript:;" class="remove">
				</a>
			</div>
		</div>
		<div class="portlet-body form">
					
					
					
					
					
					<!-- BEGIN SAMPLE TABLE PORTLET-->
						<div class="portlet-body flip-scroll">
							<table class="table table-bordered table-condensed flip-content" id="itemsTable">
								<thead class="flip-content bg-grey">
									<tr>
										<th width="20%">
											Shipment Item
										</th>
										<th>
											Shipment
										</th>
										<th>
											Product
										</th>
										<th>
											Quantity
										</th>
										<th>
											Cost
										</th>
										<th>
											Currency
										</th>
										<th>
											Expiry Date
										</th>
										<th>
											Condition
										</th>
									</tr>
										</thead>
											<tbody>
                    				
									
											</tbody>
							</table>
						</div>
							<!-- END SAMPLE TABLE PORTLET-->
					<hr/>
				</div>
			</div>
		</div>
			<div class="col-md-2"></div>
        </div>
				
		        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-8">
            
            <div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-left: 0px;">
              
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-right: 0px;">
              <button type="button" data-toggle="modal" href="#itemsModal" class="btn-sm green custom-right">
                Add New
                <i class="fa fa-plus"></i>
              </button>
            </div>
          </div>
          <div class="col-md-2"></div>
        </div>
		
		
			<div class="form-actions fluid">
				<div class="row">
					<div class="col-md-6">
						<div class="col-md-offset-3 col-md-9">
							<button type="submit" class="btn green">Submit</button>
							<button type="button" class="btn default">Cancel</button>
						</div>
					</div>
					<div class="col-md-6"></div>
				</div>
			</div>
		</form>
			</div>
		<!-- END FORM-->
	</div>
</div>

	<div id="partialFiller">
	<?php echo $this->render('shipments/partial/items') ?>
	</div>
<?php
$this->inlineScript ()
	->appendFile ( $this->basePath ( '/assets/scripts/shipments/shipment.js' ) )
	->appendFile ( $this->basePath ( '/assets/scripts/shipments/items.js' ) )
?>
<?php $this->inlineScript()->captureStart()?>
  jQuery(document).ready(function() {
	// User.init();
	Shipment.init();
	Items.init();

  });
<?php $this->inlineScript()->captureEnd() ?>
