<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet box grey">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-edit"></i>Shipment List
							</div>
							<div class="tools">
								<a href="javascript:;" class="collapse">
								</a>
								<a href="#portlet-config" data-toggle="modal" class="config">
								</a>
								<a href="/" class="reload">
								</a>
								<a href="javascript:;" class="remove">
								</a>
							</div>
						</div>
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="btn-group">
									<a class="btn green" href="/shipment/add">
									Add New <i class="fa fa-plus"></i>
									</a>
								</div>
							</div>
							<table class="main table table-striped table-hover table-bordered" id="shipments_table">
							<thead>
							<tr>
								<th>#</th>
								<th>Supplier</th>
								<th>Reference Number</th>
								<th>Shipment Status</th>
								<th>Arrival Date</th>
								<th>Confirmed By</th>
								<th>Approved By</th>
								<th>Notes</th>
								<th>Action</th>
							</tr>
							</thead>
							<tbody>
							<?php $i=1; foreach ($records as $record) : ?>
								 <tr>
									 <td><?php echo $i; $i++; ?></td>
									 <td><?php echo $record->getSupplier()->getSupplierName() ?></td>
									 <td><?php echo $record->getReferenceNo() ?></td>
									 <td><?php echo $record->getShipmentStatus() ?></td>
									 <td><?php echo $record->getArrivalDate()->format('Y-m-d H:i:s') ?></td>
									 <td><?php echo $record->getConfirmedBy() ?></td>
									 <td><?php echo $record->getApprovedBy() ?></td>
									 <td><?php echo $record->getShipmentNotes() ?></td>
									 <td><a class="edit" href="<?php echo $this->basePath('/shipment/edit/'.$record->getShipmentId()) ?>">Edit</a></td>
								 </tr>
							<?php endforeach; ?>
							</tbody>
							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->

<!-- BEGIN PAGE LEVEL PLUGINS -->

