<div id="paymentdetailModal" class="modal fade" tabindex="-1" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<h4 class="modal-title">Payment Details</h4>
			</div>
			<div class="modal-body">
				<div class="scroller" style="height:450px" data-always-visible="1" data-rail-visible1="1">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
							You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
							Your form validation is successful!
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
										<?php  echo $this->formRow($formPaymentDetail->get('dummyproducts')); ?>
										<span class="help-block">
											Items
										</span>
									</div>
								</div>
							</div>
							<!--/span-->
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
										<?php  echo $this->formRow($formPaymentDetail->get('dummyfile')); ?>
										<span class="help-block">
											File
										</span>
									</div>
								</div>
							</div>
						</div><!--/row  -->

						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
										<?php  echo $this->formRow($formPaymentDetail->get('dummyproduct')); ?>
										<span class="help-block">
											Product
										</span>
									</div>
								</div>
							</div>
							<!--/col-->

							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
										<?php  echo $this->formRow($formPaymentDetail->get('dummydate')); ?>
										<span class="help-block">
											Date 
										</span>
									</div>
								</div>
							</div>
						</div><!--/row  -->
						<div class="modal-footer">
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
										<?php  echo $this->formRow($formPaymentDetail->get('dummycheckno')); ?>
										<span class="help-block">
											Check No.
										</span>
									</div>
								</div>
							</div>

							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
										<?php  echo $this->formRow($formPaymentDetail->get('dummycheckdate')); ?>
										<span class="help-block">
											Total
										</span>
									</div>
								</div>
							</div>
						</div><!--/row  -->
						
						</div><!--/row  -->
						<div class="modal-footer">
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
										<?php  echo $this->formRow($formPaymentDetail->get('dummybank')); ?>
										<span class="help-block">
										Bank
										</span>
									</div>
								</div>
							</div>

							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
										<?php  echo $this->formRow($formPaymentDetail->get('dummyamount')); ?>
										<span class="help-block">
											Amount
										</span>
									</div>
								</div>
							</div>
						</div><!--/row  -->
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
										<?php  echo $this->formRow($formPaymentDetail->get('dummydepositdate')); ?>
										<span class="help-block">
										Deposit Date
										</span>
									</div>
								</div>
							</div>

							<div class="col-md-6">
								<div class="form-group">
									<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
								
									</div>
								</div>
							</div>
						</div><!--/row  -->
						
							<button type="button" data-dismiss="modal" class="btn default">Close</button>
							<button type="button" class="btn green">Save changes</button>
						</div>
					</div><!--/form body  -->
				</div><!--/scroller  -->
			</div><!--/modal body  -->
		</div><!--/modal content  -->
	</div><!--/modal dialog  -->
</div><!--/class modal  -->
