<div id="returnModal" class="modal fade" tabindex="-1" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true"></button>
				<h4 class="modal-title">Returned Items</h4>
			</div>
			<div class="modal-body">
				<form action="#" class="form-horizontal" id="return_item_add">
					<div class="form-body">
						<div class="scroller" style="height: 320px"
							data-always-visible="1" data-rail-visible1="1">

							<div class="alert alert-danger display-hide">
								<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
							</div>
							<div class="alert alert-success display-hide">
								<button class="close" data-close="alert"></button>
								Your form validation is successful!
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<div
											class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
											<?php  echo $this->formRow($formSalesItem->get('product[productId]')); ?>
											<span class="help-block"> Items </span>
										</div>
									</div>
								</div>
								<!--/span-->
								<div class="col-md-6">
									<div class="form-group">
										<div
											class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
											<?php  echo $this->formRow($formSalesItem->get('quantity')); ?>
											<span class="help-block"> Quantity </span>
										</div>
									</div>
								</div>
							</div>
							<!--/row  -->
							
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<div
											class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
											<?php  echo $this->formRow($formSalesItem->get('returnQuantity')); ?>
											<span class="help-block"> Return Quantity </span>
										</div>
									</div>
								</div>
								<!--/span-->
								<div class="col-md-6">
									<div class="form-group">
										<div
											class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
											
										</div>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<div
											class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
											<?php  echo $this->formRow($formSalesItem->get('price')); ?>
											<span class="help-block"> Price </span>
										</div>
									</div>
								</div>
								<!--/col-->

								<div class="col-md-6">
									<div class="form-group">
										<div
											class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
											<?php  echo $this->formRow($formSalesItem->get('discount')); ?>
											<span class="help-block"> Discount </span>
										</div>
									</div>
								</div>
							</div>
							<!--/row  -->

							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<div
											class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
											<?php  echo $this->formRow($formSalesItem->get('freebie')); ?>
											<span class="help-block"> Freebie </span>
										</div>
									</div>
								</div>

								<div class="col-md-6">
									<div class="form-group">
										<div
											class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
											<?php  echo $this->formRow($formSalesItem->get('sales')); ?>
											<span class="help-block"> Total </span>
										</div>
									</div>
								</div>
							</div>
							<!--/row  -->
						</div>
						<div class="modal-footer">
							<button type="button" data-dismiss="modal" class="btn default">Close</button>
							<button type="submit" class="btn green">Save changes</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

