
<!-- BEGIN EXAMPLE TABLE PORTLET-->

<div class="portlet box grey">
  <div class="portlet-title">
	<div class="caption">
	  <i class="fa fa-edit"></i>CUSTOMER LIST
	</div>
	<div class="tools">
	  <a href="javascript:;" class="collapse"> </a> <a
	  href="#portlet-config" data-toggle="modal" class="config"> </a> <a
	  href="/" class="reload"> </a> <a href="javascript:;" class="remove">
	  </a>
	</div>
  </div>
  <div class="portlet-body">
	<div class="table-toolbar">
	  <div class="btn-group">
		<a class="btn green" href="/customer/add"> Add New <i class="fa fa-plus"></i>
		</a>
	  </div>
	</div>
	<table class="main table table-striped table-hover table-bordered" id="customers_table">
	<thead>
	  <tr>
		<th>Category</th>
		<th>Type</th>
		<th>Name</th>
		<th>Trade Name</th>
		<th>Branch</th>
		<th>TIN</th>
		<th>Phone</th>
		<th>Email</th>
		<th>Website</th>
		<th>SEC No</th>
		<th>Credit Limit</th>
		<th>Transaction Limit</th>
		<th>Payment Term</th>
		<th>Shipping Mode</th>
		<th>Commission</th>
		<th>Sales Executive</th>
		<th>Price Type</th>
		<th>Status</th>
		<th></th>
		<th></th>
	  </tr>
	</thead> 
	<tbody>
	  
	  <?php  foreach ($dbCustomers as $dbCustomer) :?>
		<tr> 
		  <td><?php echo $dbCustomer->getCategory() ? $dbCustomer->getCategory()->getCategoryName() : "" ?></td>
		  <td><?php echo $dbCustomer->getCustomerType() ? $dbCustomer->getCustomerType()->getCustomerTypeName() : "" ?></td>
		  <td><?php  echo $dbCustomer->getCompanyName() ?></td>
		  <td><?php  echo $dbCustomer->getTradeName() ?></td>
		  <td><?php  echo $dbCustomer->getBranch() ?></td>
		  <td><?php  echo $dbCustomer->getTin() ?></td>
		  <td><?php  echo $dbCustomer->getPhone() ?></td>
		  <td><?php  echo $dbCustomer->getEmail() ?></td>
		  <td><?php  echo $dbCustomer->getWebsite() ?></td>
		  <td><?php  echo $dbCustomer->getSecNo() ?></td>
		  <td><?php  echo $dbCustomer->getCreditLimit() ?></td>
		  <td><?php  echo $dbCustomer->getTransactionLimit() ?></td>
		  <td><?php  echo $dbCustomer->getPaymentTerm() ? $dbCustomer->getPaymentTerm()->getPaymentTermName() : "" ?></td>
		  <td><?php  echo $dbCustomer->getShippingMode() ? $dbCustomer->getShippingMode()->getShippingModeName() : "" ?></td>
		  <td><?php  echo $dbCustomer->getPercentCommission() ?></td>
		  <td><?php  echo $dbCustomer->getSalesExecutive() ? $dbCustomer->getSalesExecutive()->getUserName() : "" ?></td>
		  <td><?php  echo $dbCustomer->getPriceType() ? $dbCustomer->getPriceType()->getPriceTypeName() : "" ?></td>
		  <td><?php  echo $dbCustomer->getCustomerStatus() ?></td>
		  <td><a class="edit"
			href=" <?php  echo  $this->basePath('/customer/edit'.$dbCustomer->getCustomerId()) ?> ">Edit</a></td>
			<td><a class="delete"
			  href=" <?php  echo $this->basePath('/customer/delete'.$dbCustomer->getCustomerId()) ?> ">Delete</a></td>
			</tr>
		  <?php endforeach; ?>
		</tbody>
	  </table>
	</div>
  </div>
  
  
