<!-- BEGIN PAGE LEVEL STYLES -->
<?php
$this->headLink()
->appendStylesheet($this->basePath('/assets/plugins/select2/select2.css'))
->appendStylesheet($this->basePath('/assets/plugins/select2/select2-metronic.css'))
->appendStylesheet($this->basePath('/assets/plugins/data-tables/DT_bootstrap.css'))
?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-reorder"></i>Sales Profile
    </div>
    <div class="tools">
      <a href="javascript:;" class="collapse">
      </a>
      <a href="#portlet-config" data-toggle="modal" class="config">
      </a>
      <a href="javascript:;" class="reload">
      </a>
      <a href="javascript:;" class="remove">
      </a>
    </div>
  </div>
  <div class="portlet-body form">
    <!-- BEGIN FORM-->
    <form action="#" class="form-horizontal">
      <div class="form-body">
        <h4 class="form-section">General Info  </h4>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('sono')); ?>
                <span class="help-block">
                  SO Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($form->get('transaction_types[transaction_type_id]')); ?>
                <span class="help-block">
                  Transaction Type
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>


        <div id="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('customers[customer_id]')); ?>
                <span class="help-block">
                  Customer
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($form->get('inventory_locations[location_id]')); ?>
                <span class="help-block">
                  Inventory Location
                </span>
              </div>
            </div>
          </div>
        </div>



        <div id="row">  
          <div class="col-md-12">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                <?php  echo $this->formRow($form->get('address[address_id]')); ?>
                <span class="help-block">
                  Shipping Address
                </span>
              </div>
            </div>
          </div>
        </div>

        <div id="row">
          <div class="col-md-12">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                <?php  echo $this->formRow($form->get('address[address_id]')); ?>
                <span class="help-block">
                  Billing Address
                </span>
              </div>
            </div>
          </div>
        </div>
        <div id="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('order_source[order_source_id]')); ?>
                <span class="help-block">
                  Order Source
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($form->get('shipping_modes[shipping_mode_id]')); ?>
                <span class="help-block">
                  Shipping Mode
                </span>
              </div>
            </div>
          </div>
        </div>

        <div id="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('sales[sales_executive_id]')); ?>
                <span class="help-block">
                  Sales Executive
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($form->get('sales[payment_term_id]')); ?>
                <span class="help-block">
                  Payment Terms
                </span>
              </div>
            </div>
          </div>
        </div>


        <div id="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('sales[delivery_date]')); ?>
                <span class="help-block">
                  Delivery Date
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($form->get('sales[ordered_by]')); ?>
                <span class="help-block">
                  Ordered By
                </span>
              </div>
            </div>
          </div>
        </div>

        <div id="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($form->get('price_types[price_type_id]')); ?>
                <span class="help-block">
                  Price Type
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($form->get('sales[promo_id]')); ?>
                <span class="help-block">
                  Promo
                </span>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <div class="col-md-2 col-lg-2 "></div>
              <div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 ">
                <?php echo $this->formRow($form->get('sales_notes')); ?>
                <span class="help-block">
                  Notes
                </span>
              </div>
              <div class="col-md-2 col-lg-2 "></div>
            </div>
          </div>
        </div>


        <div class="row form-section">
          <div class="col-md-12">
            <div class="col-xs-6 col-sm-6 col-md-6 col-md-6">
              <h4 class="">Ordered Items</h4>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-md-6">
              <button id="kalabaw" type="button" data-toggle="modal" href="#oderedItemsModal" class="btn-sm green custom-right">

                <i class="fa fa-plus"></i>
              </button>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-2"></div>
          <div class="col-md-8">
            <div class="row">
              <div class="col-md-12">
                <!-- BEGIN SAMPLE TABLE PORTLET-->
                <div class="portlet-body flip-scroll">
                  <table class="table table-bordered table-condensed flip-content">
                    <thead class="flip-content bg-grey">
                      <tr>
                        <th width="20%">
                          Items
                        </th>
                        <th>
                          Quantity
                        </th>
                        <th width="12%">
                          Price
                        </th>
                        <th width="12%">
                          Discoumt
                        </th>
                        <th width="12%">
                          Freebie
                        </th>
                        <th width="12%">
                          Total
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($oderedItems as $item) : ?>
                        <tr>
                          <td><?php //echo $this->escapeHtml($item->getChildProduct()->getProductName()); ?></td>
                          <td><?php //echo $this->escapeHtml($item->getBundleQuantity()); ?></td>
                          <td><?php //echo $this->escapeHtml($item->getBundleQuantity()); ?></td>
                          <td><?php //echo $this->escapeHtml($item->getBundleQuantity()); ?></td>
                          <td><?php //echo $this->escapeHtml($item->getBundleQuantity()); ?></td>
                          <td><?php //echo $this->escapeHtml($item->getBundleQuantity()); ?></td>
                          <td><a id="" data-toggle="modal" href="#" class="btn-sm green custom-right">
                            Delete
                            <i class="fa fa-times"></i>
                          </a></td>

                        </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
                </div>
                <!-- END SAMPLE TABLE PORTLET-->
              </div>
            </div>
          </div>
          <div class="col-md-2"></div>
        </div>


        <div class="row">
          <div id="row">
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 right">
                  <?php  echo $this->formRow($form->get('vatPercentage[vatPercentageId]')); ?>
                  <span class="help-block">
                    VAT Percentage
                  </span>
                </div>
              </div>
            </div>




            <div class="col-md-12">
              <div class="form-group">
                <div class="col-md-2 col-lg-2 "></div>
                <div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 right">
                  <?php  echo $this->formRow($form->get('items')); ?>
                  <span class="help-block">
                    Items
                  </span>
                </div>
                <div class="  col-md-2 col-lg-2 "></div>
              </div>
            </div>

            <div class="col-md-12">
              <div class="form-group">
                <div class="col-md-2 col-lg-2 "></div>
                <div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 right">
                  <?php  echo $this->formRow($form->get('sales')); ?>
                  <span class="help-block">
                    Sales
                  </span>
                </div>
                <div class="col-md-2 col-lg-2 "></div>
              </div>
            </div>

            <div class="col-md-12">
              <div class="form-group">
                <div class="col-md-2 col-lg-2 "></div>
                <div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 right">
                  <?php  echo $this->formRow($form->get('vat')); ?>
                  <span class="help-block">
                    VAT
                  </span>
                </div>
                <div class="col-md-2 col-lg-2 "></div>
              </div>
            </div>

            <div class="col-md-12">
              <div class="form-group">
                <div class="col-md-2 col-lg-2 "></div>
                <div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 right">
                  <?php  echo $this->formRow($form->get('total')); ?>
                  <span class="help-block">
                    Total
                  </span>
                </div>
                <div class="col-md-2 col-lg-2 "></div>
              </div>
            </div>
          </div>


          <!-- BEGIN PAGE CONTENT-->

        </div>      <!--/FORM BODY  -->

        <div class="form-actions fluid">
          <div class="row">
            <div class="col-md-6">
              <div class="col-md-offset-3 col-md-9">
                <button type="button" class="btn green">Submit</button>
                <button type="button" class="btn default">Cancel</button>
              </div>
            </div>
            <div class="col-md-6">
            </div>
          </div>
        </div>
      </form>
      <!-- END FORM-->
    </div>
  </div>
  <?php echo $this->render('sales/order') ?>


  <!-- BEGIN PAGE LEVEL PLUGINS -->
  <!-- END PAGE LEVEL PLUGINS -->
  <!-- BEGIN PAGE LEVEL SCRIPTS -->
  <?php
  $this->inlineScript()
  ->appendFile($this->basePath('/assets/scripts/product.js'))
  ?>
  <?php $this->inlineScript()->captureStart() ?>
  jQuery(document).ready(function() {
    App.init();
    Product.init();
    ComponentsEditors.init();
    $('.tags').tagsInput({
      width: '100%',
    });
  });
  <?php $this->inlineScript()->captureEnd() ?>
