
<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>Purchase Order
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse"></a> <a
				href="#portlet-config" data-toggle="modal" class="config"></a> <a
				href="javascript:;" class="reload"></a> <a href="javascript:;"
				class="remove"></a>
		</div>
	</div>
	<div class="portlet-body form">
		<form action="/user/add" method="post" class="form-horizontal"
			id="user_add">
			<div class="form-body">
				<div class="alert alert-danger display-hide">
					<button class="close" data-close="alert"></button>
					You have some form errors. Please check below.
				</div>
				<div class="alert alert-success display-hide">
					<button class="close" data-close="alert"></button>
					Your form validation is successful!
					<!-- </div> -->
					<!<div class="row"> -->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($purchaseForm->get('purchaseId')); ?>
								<span class="col-md-12 control-label">purchase</span>
							</div>
						</div>	
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($purchaseForm->get('supplierId')); ?>
								<span class="col-md-12 control-label">supplier</span>
							</div>
						</div>
					</div>
				</div>
					<!<div class="row"> -->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($purchaseForm->get('referenceNo')); ?>
								<span class="col-md-12 control-label">Reference No.</span>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($purchaseForm->get('purchaseDate')); ?>
								<span class="col-md-12 control-label">Purchase Date</span>
							</div>
						</div>
					</div>
				</div>
									<!<div class="row"> -->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($purchaseForm->get('expectedArrivalDate')); ?>
								<span class="col-md-12 control-label">Expected Arrival Date</span>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($purchaseForm->get('purchaseStatus')); ?>
								<span class="col-md-12 control-label">Purchase Status</span>
							</div>
						</div>
					</div>
				</div>
									<!<div class="row"> -->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($purchaseForm->get('purchaseNotes')); ?>
								<span class="col-md-12 control-label">Purchase Notes</span>
							</div>
						</div>
					</div>
				
				<!-- 		</form> -->
				<!-- END FORM-->
			</div>
	
	</div>
	<div id="partialFiller">
<?php echo $this->render('partial/access') ?>
</div>
<?php
$this->inlineScript ()
// 	->appendFile ( $this->basePath ( '/assets/scripts/users/user.js' ) )
// 	->appendFile ( $this->basePath ( '/assets/scripts/users/access.js' ) )
?>
<?php $this->inlineScript()->captureStart()?>
  jQuery(document).ready(function() {
	User.init();
	Access.init();

  });
<?php $this->inlineScript()->captureEnd() ?>
