<!-- BEGIN PAGE LEVEL STYLES -->
<?php
$this->headLink()
->appendStylesheet($this->basePath('/assets/plugins/select2/select2.css'))
->appendStylesheet($this->basePath('/assets/plugins/select2/select2-metronic.css'))
->appendStylesheet($this->basePath('/assets/plugins/data-tables/DT_bootstrap.css'))
?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-reorder"></i>Sales
    </div>
    <div class="tools">
      <a href="javascript:;" class="collapse">
      </a>
      <a href="#portlet-config" data-toggle="modal" class="config">
      </a>
      <a href="javascript:;" class="reload">
      </a>
      <a href="javascript:;" class="remove">
      </a>
    </div>
  </div>
  <div class="portlet-body form">
    <!-- BEGIN FORM-->
    <form action="#" class="form-horizontal">
      <div class="form-body">
        <div class="alert alert-danger display-hide">
          <button class="close" data-close="alert"></button>
            You have some form errors. Please check below.
        </div>
        <div class="alert alert-success display-hide">
          <button class="close" data-close="alert"></button>
            Your form validation is successful!
        </div>
        <h4 class="form-section">Sales Delivery </h4>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($formSales->get('drno')); ?>
                <span class="col-md-12 control-label">
                  DR Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($formSales->get('sino')); ?>
                <span class="col-md-12 control-label">
                  SI Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                  <?php  echo $this->formRow($formSales->get('sono')); ?>
                  <span class="col-md-12 control-label">
                    SO Number
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                  <?php  echo $this->formRow($formSales->get('transactionTypes[transactionTypeId]')); ?>
                  <span class="col-md-12 control-label">
                    Transaction Type
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
          </div>


          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                  <?php  echo $this->formRow($formSales->get('customers[customerId]')); ?>
                  <span class="col-md-12 control-label">
                    Customer
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                  <?php  echo $this->formRow($formSales->get('inventoryLocations[inventoryLocationId]')); ?>
                  <span class="col-md-12 control-label">
                    Inventory Location
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
          </div>


          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <div class="col-md-2 col-lg-2 "></div>
                <div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 ">
                  <?php  echo $this->formRow($formSales->get('shippingAddress[addressId]')); ?>
                  <span class="col-md-12 control-label">
                    Shipping Address
                  </span>
                </div>
                <div class="col-md-2 col-lg-2 "></div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <div class="col-md-2 col-lg-2 "></div>
                <div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 ">
                  <?php  echo $this->formRow($formSales->get('billingAddress[addressId]')); ?>
                  <span class="col-md-12 control-label">
                    Billing Address
                  </span>
                </div>
                <div class="col-md-2 col-lg-2 "></div>
              </div>
            </div>
          </div>


          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                  <?php  echo $this->formRow($formSales->get('orderSource[orderSourceId]')); ?>
                  <span class="col-md-12 control-label">
                    Order Source
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                  <?php  echo $this->formRow($formSales->get('shippingModes[shippingModeId]')); ?>
                  <span class="col-md-12 control-label">
                    Shipping Mode
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                  <?php  echo $this->formRow($formSales->get('users[userId]')); ?>
                  <span class="col-md-12 control-label">
                    Sales Executive
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                  <?php  echo $this->formRow($formSales->get('paymentTerms[paymentTermId]')); ?>
                  <span class="col-md-12 control-label">
                    Payment Terms
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
          </div>


          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                  <?php  echo $this->formRow($formSales->get('deliveryDate')); ?>
                  <span class="col-md-12 control-label">
                    Delivery Date
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                  <?php  echo $this->formRow($formSales->get('orderedBy')); ?>
                  <span class="col-md-12 control-label">
                    Ordered By
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                  <?php  echo $this->formRow($formSales->get('priceTypes[priceTypeId]')); ?>
                  <span class="col-md-12 control-label">
                    Price Type
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                  <?php  echo $this->formRow($formSales->get('percentVat')); ?>
                  <span class="col-md-12 control-label">
                    VAT Percentage
                  </span>
                </div>
              </div>

            </div>
            <!--/span-->
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <div class="col-md-2 col-lg-2 "></div>
                <div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 ">
                  <?php echo $this->formRow($formSales->get('notes')); ?>
                  <span class="col-md-12 control-label">
                    Notes
                  </span>
                </div>
                <div class="col-md-2 col-lg-2 "></div>
              </div>
            </div>
          </div>




          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <hr/>
              <div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-left: 0px;">
                <h4 class="">Ordered Items</h4>
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-right: 0px;">
                <button type="button" data-toggle="modal" href="#itemsModal" class="btn-sm green custom-right">
                  Add New
                  <i class="fa fa-plus"></i>
                </button>
              </div>
            </div>
            <div class="col-md-2"></div>
          </div>




          <div class="form-group">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <div class="row">
                <div class="col-md-12">
                  <!-- BEGIN SAMPLE TABLE PORTLET-->
                  <div class="portlet-body flip-scroll">
                    <table class="table table-bordered table-condensed flip-content">
                      <thead class="flip-content bg-grey">
                        <tr>
                          <th width="20%">
                            Items
                          </th>
                          <th>
                            Quantity
                          </th>
                          <th>
                            Price
                          </th>
                          <th>
                            Discount
                          </th>
                          <th>
                            Freebie
                          </th>
                          <th>
                            Total
                          </th>

                        </tr>
                      </thead>
                      <tbody>

                      </tbody>
                    </table>
                  </div>
                  <!-- END SAMPLE TABLE PORTLET-->
                </div>
              </div>
              <hr>
            </div>
            <div class="col-md-2"></div>
          </div>



          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                  <?php  echo $this->formRow($formSales->get('sales')); ?>
                  <span class="col-md-12 control-label">
                    Sales
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">

                  <?php  echo $this->formRow($formSales->get('items')); ?>
                  <span class="col-md-12 control-label">
                    Items
                  </span>

                </div>
              </div>
            </div>
            <!--/span-->
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                  <?php  echo $this->formRow($formSales->get('totalVat')); ?>
                  <span class="col-md-12 control-label">
                    VAT
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                  <?php  echo $this->formRow($formSales->get('totalSales')); ?>
                  <span class="col-md-12 control-label">
                    Total
                  </span>
                </div>
              </div>
            </div>
            <!--/span-->
          </div>


          <!-- BEGIN PAGE CONTENT-->

        </div>      <!--/FORM BODY  -->

        <div class="form-actions fluid">
          <div class="row">
            <div class="col-md-6">
              <div class="col-md-offset-3 col-md-9">
                <button type="button" class="btn green">Print</button>
                <button type="button" class="btn default">Cancel</button>
              </div>
            </div>
            <div class="col-md-6">
            </div>
          </div>
        </div>
      </form>
      <!-- END FORM-->
    </form><!-- end form -->
  </div><!-- porrtlet body form-->
</div><!-- end form-->
  <?php echo $this->render('sales/items') ?>


  <!-- BEGIN PAGE LEVEL PLUGINS -->
  <!-- END PAGE LEVEL PLUGINS -->
  <!-- BEGIN PAGE LEVEL SCRIPTS -->
  <?php
  $this->inlineScript()
  ->appendFile($this->basePath('/assets/scripts/product.js'))
  ?>
  <?php $this->inlineScript()->captureStart() ?>
  jQuery(document).ready(function() {
    App.init();
    Delivery.init();
    ComponentsEditors.init();
    $('.tags').tagsInput({
      width: '100%',
    });
  });
  <?php $this->inlineScript()->captureEnd() ?>
