<link href="../../assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>

			<!-- BEGIN PAGE CONTENT-->
			<div class="invoice">
				<div class="row invoice-logo">
					<div class="col-xs-6 invoice-logo-space">
						<img src="/assets/img/logo/beautylane.png " alt="logo" class="img-responsive" width="200px">
					</div>
					<div class="col-xs-6">
							<p>
							SALES INVOICE
							</p>
							<p>
							 No. 5652256 
							 </p>
							  28 Feb 2013
							<span class="muted">
								 Consectetuer adipiscing elit
							</span>
						
					</div>
				</div>
				<hr/>
				<div class="row">
					<div class="col-xs-6">
						<h4>Client Name:</h4>
						<ul class="list-unstyled">
							<li>
								 John Doe
							</li>
							<li>
								Billing Address
							</li>
						</ul>
					</div>
					<div class="col-xs-6 invoice-payment">
						<h4>Shipping Name:</h4>
						<ul class="list-unstyled">
							<li>
								 Lester Mercado
							</li>
							<li>
								 Shipping Address
							</li>
						</ul>
					</div>
				</div>
				<div class="row">
				<table class="table table-striped table-hover">
						<tbody>
						<tr>
							<td>S.O. No.:<td>
							<td>P.O. No.:</td>
							<td>Reference No.:</td>
							<td>Ordered by: </td>
						</tr>
						<tr>
							<td>Terms: </td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						</tbody>
				</table>
				</div>
				
				<div class="row">
					<div class="col-xs-12">
						<table class="table table-striped table-hover">
						<thead>
						<tr>
							<th>
								 #
							</th>
							<th>
								 Code
							</th>
							<th class="hidden-480">
								 Product
							</th>
							<th class="hidden-480">
								 Brand
							</th>
							<th class="hidden-480">
								 Description
							</th>
							<th>
								 UOM
							</th>
							<th>
								 Quantity
							</th>
						</tr>
						</thead>
						<tbody>
						<tr>
							<td>
								 1
							</td>
							<td>
								 Hardware
							</td>
							<td class="hidden-480">
								 Server hardware purchase
							</td>
							<td class="hidden-480">
								 32
							</td>
							<td class="hidden-480">
								 $75
							</td>
							<td>
								 $2152
							</td>
							<td>
								 $2152
							</td>
						</tr>
						<tr>
							<td>
								 2
							</td>
							<td>
								 Furniture
							</td>
							<td class="hidden-480">
								 Office furniture purchase
							</td>
							<td class="hidden-480">
								 15
							</td>
							<td class="hidden-480">
								 $169
							</td>
							<td>
								 $4169
							</td>
							<td>
								 $2152
							</td>
						</tr>
						<tr>
							<td>
								 3
							</td>
							<td>
								 Foods
							</td>
							<td class="hidden-480">
								 Company Anual Dinner Catering
							</td>
							<td class="hidden-480">
								 69
							</td>
							<td class="hidden-480">
								 $49
							</td>
							<td>
								 $1260
							</td>
							<td>
								 $2152
							</td>
						</tr>
						<tr>
							<td>
								 3
							</td>
							<td>
								 Software
							</td>
							<td class="hidden-480">
								 Payment for Jan 2013
							</td>
							<td class="hidden-480">
								 149
							</td>
							<td class="hidden-480">
								 $12
							</td>
							<td>
								 $866
							</td>
							<td>
								 $2152
							</td>
						</tr>
						</tbody>
						</table>
					</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-xs-4">
					</div>
					<div class="col-xs-8 invoice-block">
						<br/>
						<a class="btn btn-lg blue hidden-print" onclick="javascript:window.print();">
							 Print <i class="fa fa-print"></i>
						</a>
						<a class="btn btn-lg green hidden-print">
							 Submit Your Invoice <i class="fa fa-check"></i>
						</a>
					</div>
				</div>
			</div>
			<!-- END PAGE CONTENT-->
		
	<!-- END CONTENT -->

<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->

<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="assets/plugins/respond.min.js"></script>
<script src="assets/plugins/excanvas.min.js"></script> 
<![endif]-->

<!-- END CORE PLUGINS -->
<script src="../../assets/scripts/core/app.js"></script>
<script>
jQuery(document).ready(function() {    
 //  App.init();
});
</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>