<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-edit"></i>CUSTOMER LIST
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse"> </a> <a
				href="#portlet-config" data-toggle="modal" class="config"> </a> <a
				href="/" class="reload"> </a> <a href="javascript:;" class="remove">
			</a>
		</div>
	</div>
	<div class="portlet-body">
		<div class="table-toolbar">
			<div class="btn-group">
				<a class="btn green" href="/customer/add"> Add New <i
					class="fa fa-plus"></i>
				</a>
			</div>
		</div>
		<table class="main table table-striped table-hover table-bordered"
			id="customers_table">
			<thead>
				<tr>
					<th>SO Number</th>
					<th>Transaction Type</th>
					<th>Customer</th>
					<th>Inventory Location</th>
					<th>Shipping Address</th>
					<th>Billing Address</th>
					<th>Order Source</th>
					<th>Shipping Mode</th>
					<th>Sales Executive</th>
					<th>Payment Terms</th>
					<th>Delivery Date</th>
					<th>Ordered By</th>
					<th>Price Type</th>
					<th>VAT Percentage</th>
					<th>Ordered Items</th>
					<th>Sales</th>
					<th>Items</th>
					<th>Vat</th>
					<th>Total</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
	  
	  <?php  foreach ($records as $record) :?>
		<tr>
					<td><?php echo $record->getCustomerType() ? $record->getCustomerType()->getCustomerTypeName() : "" ?></td>
					<td><?php  echo $record->getCompanyName() ?></td>
			
					<td><a class="edit"
						href=" <?php // echo  $this->basePath('/customer/edit'.$record->getCustomerId()) ?> ">Edit</a></td>
					<td><a class="delete"
						href=" <?php // echo $this->basePath('/customer'.$record->getCustomerId()) ?> ">Delete</a></td>
				</tr>
		  <?php endforeach; ?>
		</tbody>
		</table>
	</div>
</div>






