<!-- BEGIN PAGE LEVEL STYLES -->
<?php
$this->headLink()
->appendStylesheet($this->basePath('/assets/plugins/select2/select2.css'))
->appendStylesheet($this->basePath('/assets/plugins/select2/select2-metronic.css'))
->appendStylesheet($this->basePath('/assets/plugins/data-tables/DT_bootstrap.css'))
?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-reorder"></i>Payment Records
    </div>
    <div class="tools">
      <a href="javascript:;" class="collapse">
      </a>
      <a href="#portlet-config" data-toggle="modal" class="config">
      </a>
      <a href="javascript:;" class="reload">
      </a>
      <a href="javascript:;" class="remove">
      </a>
    </div>
  </div>
  <div class="portlet-body form">
    <!-- BEGIN FORM-->
    <form action="#" class="form-horizontal">
      <div class="form-body">
          <div class="alert alert-danger display-hide">
            <button class="close" data-close="alert"></button>
              You have some form errors. Please check below.
          </div>
          <div class="alert alert-success display-hide">
            <button class="close" data-close="alert"></button>
              Your form validation is successful!
          </div>
        <h4 class="form-section">Records  </h4>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($formSales->get('paymentNo')); ?>
                <span class="col-md-12 control-label">
                  Payment Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->

            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                  <?php  echo $this->formRow($formSales->get('proformaInvoiceNo')); ?>
                  <span class="col-md-12 control-label">
                    Performa Invoice Number
                  </span>
                </div>
              </div>
            </div>
          <!--/span-->
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($formSales>get('cmNo')); ?>
                <span class="col-md-12 control-label">
                  CM Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($formSales->get('rmrNo')); ?>
                <span class="col-md-12 control-label">
                  RMR Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>


        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($formSales->get('drNo')); ?>
                <span class="col-md-12 control-label">
                DR Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($formSales->get('siNo')); ?>
                <span class="col-md-12 control-label">
                SI Number
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($formSales->get('soNo')); ?>
                <span class="col-md-12 control-label">
                SO Number testing
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($formSales->get('transactionTypes[transactionTypeId]')); ?>
                <span class="col-md-12 control-label">
              Transaction Types
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>


        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($formSales->get('customers[customerId]')); ?>
                <span class="col-md-12 control-label">
                Customer
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($formSales->get('deliveryDates[deliveryDateId]')); ?>
                <span class="col-md-12 control-label">
              Delivery Date
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($formSales->get('vatPercentage[vatPercentageId]')); ?>
                <span class="col-md-12 control-label">
                Vat Percentage
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($formSales->get('items')); ?>
                <span class="col-md-12 control-label">
                Items
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                  <?php  echo $this->formRow($formSales->get('sales')); ?>
                  <span class="col-md-12 control-label">
                  Sales
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
                <?php  echo $this->formRow($formSales->get('vat')); ?>
                <span class="col-md-12 control-label">
                VAT
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
                <?php  echo $this->formRow($formSales->get('transactionTypes[transactionTypeId]')); ?>
                <span class="col-md-12 control-label">
                  Total
                </span>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>
          <!-- BEGIN PAGE CONTENT-->

        </div>      <!--/FORM BODY  -->

        <div class="form-actions fluid">
          <div class="row">
            <div class="col-md-6">
              <div class="col-md-offset-3 col-md-9">
                <button type="button" class="btn green">Save and Send</button>
                <button type="button" class="btn default">Cancel</button>
              </div>
            </div>
            <div class="col-md-6">
            </div>
          </div>
        </div>
      </form><!-- end form -->
    </div><!-- end portlet body-->
</div><!-- portlet box grey -->


  <!-- BEGIN PAGE LEVEL PLUGINS -->
  <!-- END PAGE LEVEL PLUGINS -->
  <!-- BEGIN PAGE LEVEL SCRIPTS -->
  <?php
  $this->inlineScript()
  ->appendFile($this->basePath('/assets/scripts/payment.js'))
  ?>
  <?php $this->inlineScript()->captureStart() ?>
  jQuery(document).ready(function() {

    $('.tags').tagsInput({
      width: '100%',
    });
  });
  <?php $this->inlineScript()->captureEnd() ?>
