<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>PAYMENT RECORD
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse"></a> 
			<a href="#portlet-config" data-toggle="modal" class="config"> </a> 
			<a href="javascript:;" class="reload"> </a> <a href="javascript:;" class="remove"> </a>
		</div>
	</div>

	<div class="portlet-body form">
		<!-- BEGIN FORM-->
		<form action="/sales/order/add" method="post" class="form-horizontal" id="order_add">
			<div class="form-body">
				<div class="alert alert-danger display-hide">
					<button class="close" data-close="alert"></button>
					You have some form errors. Please check below.
				</div>
				<div class="alert alert-success display-hide">
					<button class="close" data-close="alert"></button>
					Your form validation is successful!
				</div>
				
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($formSales->get('deliveryDate')); ?>
				                <span class="col-md-12 control-label"> Delivery Date </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($formSales->get('drno')); ?>
								<span class="col-md-12 control-label"> DR Number </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($formSales->get('sono')); ?>
					            <span class="col-md-12 control-label"> SO Number </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
				                <?php  echo $this->formRow($formSales->get('transactionType[transactionTypeId]')); ?>
				                <span class="col-md-12 control-label"> Transaction Type </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($formSales->get('orderedBy')); ?>
				                <span class="col-md-12 control-label"> Ordered By </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
				                <?php  echo $this->formRow($formSales->get('inventoryLocation[locationId]')); ?>
				                <span class="col-md-12 control-label"> Inventory Location </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($formSales->get('user[salesExecutiveId]')); ?>
				                <span class="col-md-12 control-label"> Sales Executive </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
				    			<?php  echo $this->formRow($formSales->get('orderSource[orderSourceId]')); ?>
				                <span class="col-md-12 control-label"> Order Source </span>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
				                <?php  echo $this->formRow($formSales->get('shippingMode[shippingModeId]')); ?>
				                <span class="col-md-12 control-label"> Delivery Method </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>

				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<div class="col-md-2 col-lg-2 "></div>
							<div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 ">
				                <?php echo $this->formRow($formSales->get('salesNotes')); ?>
				                <span class="col-md-12 control-label"> Special Instructions </span>
							</div>
							<div class="col-md-2 col-lg-2 "></div>
						</div>
					</div>
				</div>

				<br />
				<br />
				<br />
				<br />

				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<div class="col-md-2 col-lg-2 "></div>
							<div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 ">
				                <?php  echo $this->formRow($formSales->get('customer[customerId]')); ?>
				                <span class="col-md-12 control-label"> Customer </span>
							</div>
							<div class="col-md-2 col-lg-2 "></div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<div class="col-md-2 col-lg-2 "></div>
							<div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 ">
				                <?php  echo $this->formRow($formSales->get('shippingAddressId')); ?>
				                <span class="col-md-12 control-label"> Shipping Address </span>
							</div>
							<div class="col-md-2 col-lg-2 "></div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<div class="col-md-2 col-lg-2 "></div>
							<div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 ">
				                <?php  echo $this->formRow($formSales->get('billingAddressId')); ?>
				                <span class="col-md-12 control-label"> Billing Address </span>
							</div>
							<div class="col-md-2 col-lg-2 "></div>
						</div>
					</div>
				</div>

				<!-- 	BEGIN ORDERED ITEMS -->
				<div class="portlet box grey">
					<div class="portlet-title">
						<div class="caption">
							<i class="fa fa-reorder"></i>ORDERED ITEMS
						</div>
						<div class="tools">
							<a href="javascript:;" class="collapse"> </a> 
							<a href="#portlet-config" data-toggle="modal" class="config"> </a>
							<a href="javascript:;" class="reload"> </a> 
							<a href="javascript:;" class="remove"> </a>
						</div>
					</div>
					<div class="portlet-body form">
						<!-- BEGIN FORM-->
						<div class="form-body">
							<div class="row">
								<div class="col-md-2"></div>
								<div class="col-md-8">
									<div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-left: 0px;">
<!-- 										<button type="button" data-toggle="modal" href="#itemsModal" -->
<!-- 											class="btn-sm green custom-left"> -->
<!-- 											Add New <i class="fa fa-plus"></i> -->
<!-- 										</button> -->
									</div>
									<div class="col-xs-6 col-sm-6 col-md-6 col-md-6" style="padding-right: 0px;"></div>
								</div>
								<div class="col-md-2"></div>
							</div>
							<div class="form-group">
								<div class="col-md-2"></div>
								<div class="col-md-8">
									<div class="row">
										<br />
										<div class="col-md-12">
											<div class="portlet-body flip-scroll">
												<table id="orderTable" class="table table-bordered table-condensed flip-content">
													<thead class="flip-content bg-grey">
														<tr>
															<th width="20%">Code</th>
															<th>Product Order</th>
															<th>Quantity</th>
															<th>Unit Price</th>
															<th>Total</th>
															<th width="12%">Action</th>
														</tr>
													</thead>
													<tbody>
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
								<div class="col-md-2"></div>
							</div>
						</div>
						<!-- END FORM-->
					</div>
				</div>
				<!-- 	END ORDERED ITEMS -->

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">

							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
							<?php  echo $this->formRow($formSales->get('discount')); ?>
							<span class="col-md-12 control-label"> Discount </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">

							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
							<?php  echo $this->formRow($formSales->get('totalVat')); ?>
							<span class="col-md-12 control-label"> VATable Sales </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">

							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($formSales->get('totalVat')); ?>
								<span class="col-md-12 control-label"> VAT Exempt Sales </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">

							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($formSales->get('totalVat')); ?>
								<span class="col-md-12 control-label"> Zero-Rated Sales </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">

							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($formSales->get('totalSales')); ?>
								<span class="col-md-12 control-label"> TOTAL AMOUNT DUE </span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->
			</div>

			<div class="form-actions fluid">
				<div class="row">
					<div class="col-xs-10 col-sm-10 col-md-11 col-lg-11">
						<div class="custom-right">
							<button type="button" class="btn default">Cancel</button>
							<button type="submit" class="btn green">Approve & Send</button>				
						</div>
					</div>
					<div class="col-md-6"></div>
				</div>
			</div>

		</form>
		<!-- end form -->
	</div>
	<!-- portlet body form-->
</div>
<!-- end form body -->



<?php echo $this->render('sales/items')?>


<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<?php
$this->inlineScript ()
	->appendFile ( $this->basePath ( '/assets/scripts/sales/order.js' ) )
	->appendFile ( $this->basePath ( '/assets/scripts/sales/orderitem.js' ) )

?>
<?php $this->inlineScript()->captureStart()?>
jQuery(document).ready(function() {
  Order.init();
  OrderItem.init();
});
<?php $this->inlineScript()->captureEnd()?>
