<!-- BEGIN PAGE LEVEL STYLES -->
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet box grey">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-edit"></i>LIST OF RETURNED MERCHANDISE
							</div>
							<div class="tools">
								<a href="javascript:;" class="collapse">
								</a>
								<a href="#portlet-config" data-toggle="modal" class="config">
								</a>
								<a href="/" class="reload">
								</a>
								<a href="javascript:;" class="remove">
								</a>
							</div>
						</div>
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="btn-group">
									<a id="sample_editable_1_new" class="btn green" href="/sales/return/add">
									Add New <i class="fa fa-plus"></i>
									</a>
								</div>
								<div class="btn-group pull-right">
									<button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
									</button>
									<ul class="dropdown-menu pull-right">
										<li>
											<a href="#">
												 Print
											</a>
										</li>
										<li>
											<a href="#">
												 Save as PDF
											</a>
										</li>
										<li>
											<a href="#">
												 Export to Excel
											</a>
										</li>
									</ul>
								</div>
							</div>
							<table class="table table-striped table-hover table-bordered" id="sample_editable_1">
							<thead>
							<tr>
								<th>RMR Number</th>
								<th>DR Number</th>
								<th>SI Number</th>
							    <th>SO Number</th>
								<th>Transaction Type</th>
								<th>Customer</th>
								<th>Inventory Location</th>
								<th>Shipping Address</th>
								<th>Billing Address</th>
								<th>Order Source</th>
								<th>Shipping Mode</th>
								<th>Sales Executive</th>
								<th>Payment Terms</th>
								<th>Delivery Date</th>
								<th>Ordered By</th>
								<th>Price Type</th>
								<th>VAT Percentage</th>
								<th>Ordered Items</th>
								<th>Sales</th>
								<th>Items</th>
								<th>Vat</th>
								<th>Total</th>
								<th></th>
							</tr>
							</thead>
							<tbody>
              
							 <?php // foreach ($records as $record) : ?> 
                            	 <tr>
                            	  	<th></th>
                            	  	<th></th>
                            	   	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td></td>
                                	 <td><a class="View" href="javascript:;">View</a></td>
                            	 </tr>
                          <?php // endforeach; ?> 
							</tbody>
							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->

<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- <script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script> -->
<!-- <script type="text/javascript" src="/assets/plugins/data-tables/jquery.dataTables.js"></script> -->
<!-- <script type="text/javascript" src="/assets/plugins/data-tables/DT_bootstrap.js"></script> -->
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/assets/scripts/core/app.js"></script>
<?php 
//     $this->inlineScript()
//         ->appendFile($this->basePath('/assets/scripts/datatable/Table.js'))
//         ->appendFile($this->basePath('/assets/scripts/ajax/realms.js'))
//         ->appendFile($this->basePath('/assets/scripts/ajax/generic.js'))
?>
<?php $this->inlineScript()->captureStart() ?>
    jQuery(document).ready(function() {    
   
     //   Table.init();
    });
<?php $this->inlineScript()->captureEnd() ?>