<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-edit"></i>Return List
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse"> </a>
			<a href="#portlet-config" data-toggle="modal" class="config"> </a>
			<a href="/" class="reload"> </a>
			<a href="javascript:;" class="remove"></a>
		</div>
	</div>
	<div class="portlet-body">
		<div class="table-toolbar">
			<div class="btn-group">
				<a id="sample_editable_1_new" class="btn green" href="/sales/order/add">
					Add New <i class="fa fa-plus"></i>
				</a>
			</div>
			<div class="btn-group pull-right">
				<button class="btn dropdown-toggle" data-toggle="dropdown">
					Tools <i class="fa fa-angle-down"></i>
				</button>
				<ul class="dropdown-menu pull-right">
					<li><a href="#"> Print </a></li>
					<li><a href="#"> Save as PDF </a></li>
					<li><a href="#"> Export to Excel </a></li>
				</ul>
			</div>
		</div>
		<table class="main table table-striped table-hover table-bordered" id="products_table">
			<thead>
				<tr>
					<th>#</th>
					<th>SO Number</th>
					<th>Inventory Location</th>
					<th>Order Source</th>
					<th>Sales Executive</th>
					<th>Delivery Method</th>
					<th>Delivery Date</th>
					<th>Ordered By</th>
					<th>Customer</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1;  foreach ($records as $record) : ?>
					<tr>
						<td><?php echo $i; $i++; ?></td>
						<td><?php echo $record->getSono() ?></td>
						<td><?php echo $record->getInventoryLocation() ?  $record->getInventoryLocation()->getInventoryLocationName() : "" ?></td>
						<td><?php echo $record->getOrderSource() ? $record->getOrderSource()->getOrderSourceName() : "" ?></td>
						<td><?php echo $record->getSalesExcutive() ?></td>
						<td><?php echo $record->getShippingMode() ? $record->getShippingMode()->getShippingModeName() : "" ?></td>
						<td><?php echo $record->getDeliveryDate() ?></td>
						<td><?php echo $record->getOrderedBy() ?></td>
						<td><?php echo $record->getCustomer() ? $record->getCustomer()->getCustomerName() : "" ?></td>
						<td><a class="edit" href="<?php echo $this->basePath('/sales/order/edit/'. $record->getSalesId()) ?>">Edit</a></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>