<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-edit"></i>CUSTOMER LIST
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse"> </a> <a
				href="#portlet-config" data-toggle="modal" class="config"> </a> <a
				href="/" class="reload"> </a> <a href="javascript:;" class="remove">
			</a>
		</div>
	</div>
	<div class="portlet-body">
		<div class="table-toolbar">
			<div class="btn-group">
				<a class="btn green" href="/customer/add"> Add New <i
					class="fa fa-plus"></i>
				</a>
			</div>
		</div>
		<table class="main table table-striped table-hover table-bordered"
			id="customers_table">
			<thead>
				<tr>
					<th>SO Number</th>
					<th>DR Number</th>
					<th>SI Number</th>
					<th>RMR Number</th>
					<th>CM Number</th>
					<th>PM Number</th>
					<th>Transaction Type</th>
					<th>Customer</th>
					<th>Inventory Location</th>
					<th>Shipping Address</th>
					<!-- 10 -->
					<th>Billing Address</th>
					<th>Order Source</th>
					<th>Shipping Mode</th>
					<th>Sales Executive</th>
					<th>Payment Terms</th>
					<th>Delivery Date</th>
					<th>Ordered By</th>
					<th>Promo</th>
					<th>Price Type</th>
					<th>VAT Percentage</th>
					<!-- 20 -->
					<th>Total Items</th>
					<th>Total VAT</th>
					<th>Total Sales</th>
					<th>Total Items Returned</th>
					<th>Total VAT Returned</th>
					<th>Total Sales Returned</th>
					<th>Grand Total Sales</th>
					<th>OR No.</th>
					<th>PR No.</th>
					<th>Payment Status.</th>
					<!-- 30 -->
					<th>Transaction Status.</th>
					<th>Notes</th>		
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
	  <?php  foreach ($dbSales as $dbSalesItem) :?>
				 <tr>

					<td><?php  echo $dbSalesItem->getSono() ?></td>
					<td><?php  echo $dbSalesItem->getDrno() ?></td>
					<td><?php  echo $dbSalesItem->getSino() ?></td>
					<td><?php  echo $dbSalesItem->getRmrno() ?></td>
					<td><?php  echo $dbSalesItem->getCmno() ?></td>
					<td><?php  echo $dbSalesItem->getPmno() ?></td>
					<td><?php  echo $dbSalesItem->getTransactionType() ?></td>
					<td><?php  echo $dbSalesItem->getCustomer() ?></td>
					<td><?php  echo $dbSalesItem->getInventoryLocation() ?></td>
					<td><?php  echo $dbSalesItem->getShippingAddress() ?></td>
					<!-- 10 -->
					<td><?php  echo $dbSalesItem->getBillingAdress() ?></td>
					<td><?php  echo $dbSalesItem->getShippingModeId() ? $dbSalesItem->getShippingModeId()->getCustomerTypeName() : "" ?></td>
					<td><?php  echo $dbSalesItem->getOrderSource() ?></td>
					<td><?php  echo $dataCustomer->getSalesExecutive() ? $dataCustomer->getSalesExecutive()->getUserName() : "" ?></td>
					<td><?php  echo $dbSalesItem->getgetPaymentTerm() ?></td>
					<td><?php  echo $dbSalesItem->getgetDeliveryDate() ?></td>
					<td><?php  echo $dbSalesItem->getgetOrderedBy() ?></td>
					<td><?php  echo $dbSalesItem->getgetPromoId() ?></td>
					<td><?php  echo $dbSalesItem->getgetPriceType() ?></td>
					<td><?php  echo $dbSalesItem->getgetPercentVat() ?></td>
					<!-- 20 -->
					<td><?php  echo $dbSalesItem->getTotalItems() ?></td>
					<td><?php  echo $dbSalesItem->getTotalVat() ?></td>
					<td><?php  echo $dbSalesItem->getTotalSales() ?></td>
					<td><?php  echo $dbSalesItem->getTotalItemsReturn() ?></td>
					<td><?php  echo $dbSalesItem->getTotalVatReturn() ?></td>
					<td><?php  echo $dbSalesItem->getTotalSalesReturn() ?></td>
					<td><?php  echo $dbSalesItem->getGrandTotal() ?></td>
					<td><?php  echo $dbSalesItem->getOrno() ?></td>
					<td><?php  echo $dbSalesItem->getPrno() ?></td>
					<td><?php  echo $dbSalesItem->getgetPaymentStatus() ?></td>
					<!-- 30 -->
					<td><?php  echo $dbSalesItem->getTransactionStatus() ? $dataCustomer->getTransactionStatus()->getTransactionStatusName(): "" ?></td>
					<td><?php  echo $dbSalesItem->getgetSalesNotes() ?></td>
				
					<td><a class="edit"
						href=" <?php // echo  $this->basePath('/customer/edit'.$dbSalesItem->getCustomerId()) ?> ">Edit</a></td>
					<td><a class="delete"
						href=" <?php // echo $this->basePath('/customer'.$dbSalesItem->getCustomerId()) ?> ">Delete</a></td>
				</tr>
		  <?php endforeach; ?>
		</tbody>
		</table>
	</div>
</div>



				 	<?php  //echo $dbSalesItem->getCustomerType() ? $dbSalesItem->getCustomerType()->getCustomerTypeName() : "" ?>


