<div id="priceModal" class="modal fade" tabindex="-1" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<h4 class="modal-title">Price Type</h4>
			</div>
			<div class="modal-body">
				<div class="scroller" style="height:250px;" data-always-visible="1" data-rail-visible1="1">
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
									<?php  echo $this->formRow($form->get('priceTypes[priceTypeId]')); ?>
									<span class="help-block">
										 Price Type
									</span>
								</div>
							</div>
						</div>
							<!--/span-->
						<div class="col-md-6">
							<div class="form-group">
								<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
									<?php  echo $this->formRow($form->get('priceAmount')); ?>
									<span class="help-block">
										 Amount
									</span>
								</div>
							</div>
						</div>

						<!--/span-->
					</div>

					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
									<?php  echo $this->formRow($form->get('currencies[currencyId]')); ?>
									<span class="help-block">
										 Currency
									</span>
								</div>
							</div>
						</div>
							<!--/span-->
						</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn default">Close</button>
				<button type="button" class="btn green">Save changes</button>
			</div>
		</div>
	</div>
</div>