<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>PURCHASE
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse"></a> <a
				href="#portlet-config" data-toggle="modal" class="config"></a> <a
				href="javascript:;" class="reload"></a> <a href="javascript:;"
				class="remove"></a>
		</div>
	</div>
	<div class="portlet-body form">
		<form action="/purchase/add" method="post" class="form-horizontal"
			id="purchase_add">
			<div class="form-body">
				<div class="alert alert-danger display-hide">
					<button class="close" data-close="alert"></button>
					You have some form errors. Please check below.
				</div>
				<div class="alert alert-success display-hide">
					<button class="close" data-close="alert"></button>
					Your form validation is successful!
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($purchaseForm->get('purchase[purchaseId]')); ?>
								<span class="col-md-12 control-label">Purchase</span>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($purchaseForm->get('supplier[supplierId]')); ?>
								<span class="col-md-12 control-label">Supplier</span>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($purchaseForm->get('referenceNo')); ?>
								<span class="col-md-12 control-label">Reference Number</span>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($purchaseForm->get('purchaseDate')); ?>
								<span class="col-md-12 control-label">Purchase Date</span>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-right">
								<?php  echo $this->formRow($purchaseForm->get('expectedArrivalDate')); ?>
								<span class="col-md-12 control-label">Expected Arrival Date</span>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 custom-left">
								<?php  echo $this->formRow($purchaseForm->get('purchaseStatus')); ?>
								<span class="col-md-12 control-label">Purchase Status</span>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<div class="col-md-2 col-lg-2 "></div>
							<div class="col-md-8 col-xs-12 col-sm-12 col-lg-8 ">
									<?php echo $this->formRow($purchaseForm->get('purchaseNotes')); ?>
									<span class="col-md-12 control-label"> Description </span>
							</div>
							<div class="col-md-2 col-lg-2 "></div>
						</div>
					</div>
				</div>


				<!-- 	BEGIN DOCUMENT -->
				<div class="portlet box grey">
					<div class="portlet-title">
						<div class="caption">
							<i class="fa fa-reorder"></i>DOCUMENT
						</div>
						<div class="tools">
							<a href="javascript:;" class="collapse"> </a> <a
								href="#portlet-config" data-toggle="modal" class="config"> </a>
							<a href="javascript:;" class="reload"> </a> <a
								href="javascript:;" class="remove"> </a>
						</div>
					</div>
					<div class="portlet-body form">
						<div class="form-body">
							<div class="row">
								<br />
								<div class="col-md-2"></div>
								<div class="col-md-8">
									<div class="col-xs-6 col-sm-6 col-md-6 col-md-6"
										style="padding-left: 0px;">
										<button type="button" data-toggle="modal"
											href="#documentModal" class="btn-sm green custom-left">
											Add New <i class="fa fa-plus"></i>
										</button>
									</div>
									<div class="col-xs-6 col-sm-6 col-md-6 col-md-6"
										style="padding-right: 0px;"></div>
								</div>
								<div class="col-md-2"></div>
							</div>
							<div class="form-group">
								<div class="col-md-2"></div>
								<div class="col-md-8">
									<div class="row">
										<br />
										<div class="col-md-12">
											<div class="portlet-body flip-scroll">
												<table id="documentTable"
													class="table table-bordered table-condensed flip-content">
													<thead class="flip-content bg-grey">
														<tr>
															<th width="20%">Type</th>
															<th>File</th>
															<th>Product</th>
															<th width="10%">Remove</th>
														</tr>
													</thead>
													<tbody>
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
								<div class="col-md-2"></div>
							</div>
						</div>

						<!-- END FORM-->
					</div>
				</div>
				<!-- 	END DOCUMENT -->


				<!-- BEGIN PAGE CONTENT-->

			</div>
			<div class="form-actions fluid">
				<div class="row">
					<div class="col-md-6">
						<div class="col-md-offset-3 col-md-9">
							<button type="submit" class="btn green">Submit</button>
							<button type="button" class="btn default">Cancel</button>
						</div>
					</div>
					<div class="col-md-6"></div>
				</div>
			</div>
		</form>
		<!-- END FORM-->
	</div>
</div>


