	<div id="bundleModal" class="modal fade" tabindex="-1" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					<h4 class="modal-title">Bundle</h4>
				</div>
			<form action="#" class="form-horizontal" id="purchase_item">
				<div class="form-body">
					<div class="alert alert-danger display-hide">
						<button class="close" data-close="alert"></button>
							You have some form errors. Please check below.
					</div>
					<div class="alert alert-success display-hide">
						<button class="close" data-close="alert"></button>
							Your form validation is successful!
					</div>

				<div class="modal-body">
					<div class="scroller" style="height:150px" data-always-visible="1" data-rail-visible1="1">
						<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-right">
									<?php  echo $this->formRow($formPurchaseItem->get('purchase[purchaseId]')); ?>
									<span class="col-md-12 control-label">
										 Items Included
									</span>
								</div>
							</div>
						</div>
							<!--/span-->
						<div class="col-md-6">
							<div class="form-group">
								<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 custom-left">
									<?php  echo $this->formRow($formPurchaseItem->get('itemQuantity')); ?>
									<span class="col-md-12 control-label">
										 Quantity
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn default">Close</button>
					<button type="submit" class="btn green">Save changes</button>
				</div>
			</div> <!--/form-body  -->
			</form>
			</div>
		</div>
	</div>

